In [34]:
import pandas as pd
import numpy as np
from sklearn.model_selection import GridSearchCV, StratifiedKFold
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OrdinalEncoder
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer 
from sklearn.ensemble import VotingClassifier
from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier

Import the datas.

In [21]:
train_df = pd.read_csv("data/train.csv")
test_df = pd.read_csv("data/test.csv")
df_orig = (
    pd.read_csv('data/personality_datasert.csv')
    .rename(columns={'Personality': 'match_p'})
    .drop_duplicates(['Time_spent_Alone', 'Stage_fear', 'Social_event_attendance',
                      'Going_outside', 'Drained_after_socializing', 'Friends_circle_size',
                      'Post_frequency'])
)
print(train_df.dtypes, df_orig.dtypes)

id                             int64
Time_spent_Alone             float64
Stage_fear                    object
Social_event_attendance      float64
Going_outside                float64
Drained_after_socializing     object
Friends_circle_size          float64
Post_frequency               float64
Personality                   object
dtype: object Time_spent_Alone             float64
Stage_fear                    object
Social_event_attendance      float64
Going_outside                float64
Drained_after_socializing     object
Friends_circle_size          float64
Post_frequency               float64
match_p                       object
dtype: object

In [40]:
train_df = train_df.merge(df_orig, how='left')
test_df = test_df.merge(df_orig, how='left')
train_df

,id,Time_spent_Alone,Stage_fear,Social_event_attendance,Going_outside,Drained_after_socializing,Friends_circle_size,Post_frequency,Personality,match_p
0,0,0.0,No,6.0,4.0,No,15.0,5.0,Extrovert,NaN
1,1,1.0,No,7.0,3.0,No,10.0,8.0,Extrovert,NaN
2,2,6.0,Yes,1.0,0.0,NaN,3.0,0.0,Introvert,NaN
3,3,3.0,No,7.0,3.0,No,11.0,5.0,Extrovert,NaN
4,4,1.0,No,4.0,4.0,No,13.0,NaN,Extrovert,NaN
...,...,...,...,...,...,...,...,...,...,...
18519,18519,3.0,No,7.0,3.0,No,9.0,7.0,Extrovert,NaN
18520,18520,1.0,NaN,6.0,7.0,No,6.0,5.0,Extrovert,NaN
18521,18521,7.0,Yes,1.0,1.0,Yes,1.0,NaN,Introvert,NaN
18522,18522,NaN,Yes,1.0,0.0,Yes,5.0,2.0,Introvert,NaN
18523,18523,1.0,No,8.0,6.0,No,4.0,7.0,Extrovert,NaN

In [16]:
TARGET_COLUMN = 'Personality'
mapping = {'Introvert': 0, 'Extrovert': 1}
y = train_df[TARGET_COLUMN].map(mapping)

X = train_df.drop(["id", TARGET_COLUMN], axis=1)
X_test = test_df.drop("id", axis=1)

X['match_p_is_null'] = X['match_p'].isna().astype(int)
X_test['match_p_is_null'] = X_test['match_p'].isna().astype(int)

X_test = X_test[X.columns]

categorical_features = X.select_dtypes(include=['object', 'category']).columns
numerical_features = X.select_dtypes(include=np.number).columns 

X[categorical_features] = X[categorical_features].fillna('Unknown')
X_test[categorical_features] = X_test[categorical_features].fillna('Unknown')

numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='mean')) # Điền giá trị thiếu bằng trung bình
])

categorical_transformer = Pipeline(steps=[
    ('encoder', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1))
])

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numerical_features),
        ('cat', categorical_transformer, categorical_features)
    ],
    remainder='passthrough'
)

In [29]:
xgb_clf = XGBClassifier(use_label_encoder=False, eval_metric='logloss', random_state=42, device='cuda')
lgbm_clf = LGBMClassifier(random_state=42)
catboost_clf = CatBoostClassifier(random_state=42)

param_grid_xgb = {
    'classifier__n_estimators': [200, 300, 400],
    'classifier__learning_rate': [0.01, 0.05, 0.1],
    'classifier__max_depth': [5, 7, 10],
    'classifier__subsample': [0.7, 0.8],
    'classifier__colsample_bytree': [0.7, 0.8],
}
param_grid_lgbm = {
    'classifier__n_estimators': [200, 300, 400],
    'classifier__learning_rate': [0.01, 0.05, 0.1],
    'classifier__num_leaves': [20, 31, 40],
    'classifier__subsample': [0.7, 0.8],
    'classifier__colsample_bytree': [0.7, 0.8],
}

param_grid_catboost = {
    'classifier__iterations': [200, 300],
    'classifier__learning_rate': [0.01, 0.05],
    'classifier__depth': [4, 6, 8]
}

xgb_pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('classifier', xgb_clf)
])
lgbm_pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('classifier', lgbm_clf)
])

catboost_pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('classifier', catboost_clf)
])

In [20]:
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

print("Optimizing XGBoost...")
grid_search_xgb = GridSearchCV(xgb_pipeline, param_grid_xgb, cv=cv, scoring='accuracy', n_jobs=-1, verbose=1)
grid_search_xgb.fit(X, y)

print("\nOptimizing LightGBM...")
grid_search_lgbm = GridSearchCV(lgbm_pipeline, param_grid_lgbm, cv=cv, scoring='accuracy', n_jobs=-1, verbose=1)
grid_search_lgbm.fit(X, y)

print("\nBest XGBoost params:", grid_search_xgb.best_params_)
print("Best XGBoost score:", grid_search_xgb.best_score_)
print("\nBest LightGBM params:", grid_search_lgbm.best_params_)
print("Best LightGBM score:", grid_search_lgbm.best_score_)

Optimizing XGBoost...
Fitting 5 folds for each of 108 candidates, totalling 540 fits

/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:03] WARNING: /Users/runner/work/xgboost/xgboost/src/context.cc:203: XGBoost is not compiled with CUDA support.
  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:03] WARNING: /Users/runner/work/xgboost/xgboost/src/context.cc:203: XGBoost is not compiled with CUDA support.
  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:03] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:03] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:03] WARNING: /Users/runner/work/xgboost/xgboost/src/context.cc:203: XGBoost is not compiled with CUDA support.
  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:03] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:03] WARNING: /Users/runner/work/xgboost/xgboost/src/context.cc:203: XGBoost is not compiled with CUDA support.
  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:03] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:03] WARNING: /Users/runner/work/xgboost/xgboost/src/context.cc:203: XGBoost is not compiled with CUDA support.
  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:03] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:03] WARNING: /Users/runner/work/xgboost/xgboost/src/context.cc:203: XGBoost is not compiled with CUDA support.
  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:03] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:03] WARNING: /Users/runner/work/xgboost/xgboost/src/context.cc:203: XGBoost is not compiled with CUDA support.
  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:03] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:03] WARNING: /Users/runner/work/xgboost/xgboost/src/context.cc:203: XGBoost is not compiled with CUDA support.
  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:03] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:03] WARNING: /Users/runner/work/xgboost/xgboost/src/context.cc:203: XGBoost is not compiled with CUDA support.
  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:03] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:03] WARNING: /Users/runner/work/xgboost/xgboost/src/context.cc:203: XGBoost is not compiled with CUDA support.
  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:03] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:03] WARNING: /Users/runner/work/xgboost/xgboost/src/context.cc:203: XGBoost is not compiled with CUDA support.
  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:03] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:03] WARNING: /Users/runner/work/xgboost/xgboost/src/context.cc:203: XGBoost is not compiled with CUDA support.
  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:03] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:03] WARNING: /Users/runner/work/xgboost/xgboost/src/context.cc:203: XGBoost is not compiled with CUDA support.
  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:03] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:03] WARNING: /Users/runner/work/xgboost/xgboost/src/context.cc:203: XGBoost is not compiled with CUDA support.
  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:03] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:03] WARNING: /Users/runner/work/xgboost/xgboost/src/context.cc:203: XGBoost is not compiled with CUDA support.
  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:03] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:03] WARNING: /Users/runner/work/xgboost/xgboost/src/context.cc:203: XGBoost is not compiled with CUDA support.
  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:03] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:03] WARNING: /Users/runner/work/xgboost/xgboost/src/context.cc:203: XGBoost is not compiled with CUDA support.
  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:03] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:03] WARNING: /Users/runner/work/xgboost/xgboost/src/context.cc:203: XGBoost is not compiled with CUDA support.
  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:03] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:03] WARNING: /Users/runner/work/xgboost/xgboost/src/context.cc:203: XGBoost is not compiled with CUDA support.
  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:03] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:03] WARNING: /Users/runner/work/xgboost/xgboost/src/context.cc:203: XGBoost is not compiled with CUDA support.
  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:03] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:03] WARNING: /Users/runner/work/xgboost/xgboost/src/context.cc:203: XGBoost is not compiled with CUDA support.
  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:03] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:03] WARNING: /Users/runner/work/xgboost/xgboost/src/context.cc:203: XGBoost is not compiled with CUDA support.
  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:03] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:03] WARNING: /Users/runner/work/xgboost/xgboost/src/context.cc:203: XGBoost is not compiled with CUDA support.
  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:03] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:03] WARNING: /Users/runner/work/xgboost/xgboost/src/context.cc:203: XGBoost is not compiled with CUDA support.
  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:03] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:04] WARNING: /Users/runner/work/xgboost/xgboost/src/context.cc:203: XGBoost is not compiled with CUDA support.
  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:04] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:04] WARNING: /Users/runner/work/xgboost/xgboost/src/context.cc:203: XGBoost is not compiled with CUDA support.
  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:04] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:04] WARNING: /Users/runner/work/xgboost/xgboost/src/context.cc:203: XGBoost is not compiled with CUDA support.
  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:04] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:04] WARNING: /Users/runner/work/xgboost/xgboost/src/context.cc:203: XGBoost is not compiled with CUDA support.
  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:04] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:04] WARNING: /Users/runner/work/xgboost/xgboost/src/context.cc:203: XGBoost is not compiled with CUDA support.
  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:04] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:04] WARNING: /Users/runner/work/xgboost/xgboost/src/context.cc:203: XGBoost is not compiled with CUDA support.
  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:04] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:04] WARNING: /Users/runner/work/xgboost/xgboost/src/context.cc:203: XGBoost is not compiled with CUDA support.
  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:04] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:04] WARNING: /Users/runner/work/xgboost/xgboost/src/context.cc:203: XGBoost is not compiled with CUDA support.
  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:04] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:04] WARNING: /Users/runner/work/xgboost/xgboost/src/context.cc:203: XGBoost is not compiled with CUDA support.
  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:04] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:04] WARNING: /Users/runner/work/xgboost/xgboost/src/context.cc:203: XGBoost is not compiled with CUDA support.
  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:04] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:04] WARNING: /Users/runner/work/xgboost/xgboost/src/context.cc:203: XGBoost is not compiled with CUDA support.
  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:04] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:04] WARNING: /Users/runner/work/xgboost/xgboost/src/context.cc:203: XGBoost is not compiled with CUDA support.
  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:04] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:04] WARNING: /Users/runner/work/xgboost/xgboost/src/context.cc:203: XGBoost is not compiled with CUDA support.
  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:04] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:04] WARNING: /Users/runner/work/xgboost/xgboost/src/context.cc:203: XGBoost is not compiled with CUDA support.
  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:04] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:04] WARNING: /Users/runner/work/xgboost/xgboost/src/context.cc:203: XGBoost is not compiled with CUDA support.
  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:04] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:04] WARNING: /Users/runner/work/xgboost/xgboost/src/context.cc:203: XGBoost is not compiled with CUDA support.
  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:01:04] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

Optimizing LightGBM...
Fitting 5 folds for each of 108 candidates, totalling 540 fits
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002262 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003248 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002628 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002284 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.

[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.006553 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001068 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001179 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001248 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.003600 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.070948 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005634 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.010261 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.015776 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001046 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001950 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004049 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001117 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000465 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.023849 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005729 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004367 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003626 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001914 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.021570 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.015478 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.039226 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.008952 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.007035 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003894 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001980 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001305 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001353 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001127 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004511 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003107 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003065 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000972 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004613 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001779 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.008963 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.014394 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.006455 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004503 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001986 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10960, number of negative: 3860

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.056296 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.017483 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.034426 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001431 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001730 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003075 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002577 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002039 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.038660 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.020798 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002828 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001012 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.006745 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004654 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001432 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.016367 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.021510 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001700 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001379 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003066 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002116 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001182 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.006100 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009454 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001125 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.033093 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001097 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.006026 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002666 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004079 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.012854 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002824 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.031352 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002150 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005725 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002775 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009471 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001173 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001180 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002159 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002849 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003800 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.011397 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003883 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.027527 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004244 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002193 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004882 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.007463 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.015758 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001095 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004309 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.012978 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.065564 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.010306 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001543 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004507 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001566 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001795 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005297 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.008120 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.013939 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001160 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001319 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.007227 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001115 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005627 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001434 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.011094 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.030395 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000928 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001193 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002197 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005573 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.012129 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001446 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001235 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001367 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001330 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001827 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001497 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001826 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001499 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004081 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002100 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000953 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002255 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002278 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001876 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002144 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.007459 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.025312 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.010776 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001607 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000953 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002066 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001660 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003942 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001982 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.027525 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003884 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001057 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.006928 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001458 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002537 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.029371 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002898 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.024048 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001475 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002294 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001298 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001091 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009766 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.019800 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.019851 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003465 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001285 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001788 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005612 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001666 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.054701 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.019360 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002544 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.023767 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001712 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002001 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001065 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.014498 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005898 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001894 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001118 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001050 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009395 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005050 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004130 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.030892 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003196 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001192 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.012629 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002136 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001399 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.010364 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001585 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.027811 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.006809 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.011787 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001070 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.010985 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.010612 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.008953 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.008350 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.010746 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001350 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.012806 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003657 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009857 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.008383 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004378 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005236 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001243 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.013282 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.025982 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002034 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002308 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.017487 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001351 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004179 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001041 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001722 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003864 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001173 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001596 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001429 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001651 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001787 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004490 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001730 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002392 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003252 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001197 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000928 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001431 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.013661 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.016844 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002441 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001272 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001324 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.007369 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.017251 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001480 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001108 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003248 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001477 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.022213 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002239 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001753 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001082 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003055 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003643 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.016080 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001419 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003071 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.060391 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.012513 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001770 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.025267 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001089 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002085 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002171 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.014733 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001304 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002007 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001416 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.012929 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.013082 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001010 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.036928 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001211 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.033722 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001416 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002194 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.012338 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004278 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001385 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001420 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001008 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004491 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001353 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001152 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.030671 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005065 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.018672 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001213 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.019256 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.021042 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001381 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005383 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001252 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001810 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002474 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004933 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001260 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.027607 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001264 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001478 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001395 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9

[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.022311 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001009 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.025043 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002351 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001060 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001172 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.006867 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001079 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.023730 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004033 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001094 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009294 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.008396 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004141 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001350 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001209 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.020817 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.033133 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001241 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002749 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.035743 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.010749 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.022306 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003603 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001363 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005950 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.006782 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.025147 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001947 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001145 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001383 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001455 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001477 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001297 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.010458 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001880 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004183 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005770 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001192 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003112 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.016223 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001392 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002782 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002157 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001745 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003522 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001469 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.007410 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.007170 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001269 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001316 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001384 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000926 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001296 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001502 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001026 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002048 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001647 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.011522 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002522 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.002109 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001464 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001218 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001229 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.015058 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.017227 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.014651 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001219 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.027779 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005815 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.021598 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002032 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.056386 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.027394 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001305 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.006033 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001444 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.006188 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.005189 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.010503 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.007692 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002410 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002835 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003614 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002726 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.032406 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003138 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002768 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001753 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003093 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.006978 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.028020 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001864 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001945 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004607 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.031834 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001003 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003411 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001744 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005318 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.032794 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001282 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003721 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.012857 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002148 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003326 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.012499 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002402 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000952 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001467 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005279 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005904 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001358 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.008201 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.007953 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005216 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9

[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.010025 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.026105 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001286 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001269 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001118 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.012820 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.011287 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.015456 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.011027 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.030220 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.014198 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.[LightGBM] [Info] Number of positive: 10959, number of negative: 3860

[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.028313 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001309 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005036 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003740 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.021291 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.012739 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.027554 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.006084 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004026 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.021556 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.021222 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009761 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009563 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.012838 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003920 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.028450 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001300 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005304 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009090 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001665 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001239 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.023731 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009131 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.007042 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005193 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001379 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009410 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001468 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005292 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.024402 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001371 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000969 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.027513 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001411 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004345 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003348 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.025627 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.008663 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004607 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.028983 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.016787 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.016286 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001098 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001142 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.041567 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.023406 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002847 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003840 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002904 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.010133 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.011476 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.010973 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001909 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001741 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.003042 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001596 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.081863 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002151 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001178 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002096 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.016540 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001508 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.025492 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001121 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001078 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.012754 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.006399 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005368 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.006199 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.016618 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.027639 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001011 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002211 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001702 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.015171 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001094 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009089 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001162 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.010200 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.076818 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005082 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.006710 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.007643 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002357 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002640 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005868 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.011262 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001637 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005955 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002429 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.005733 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001424 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003075 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004331 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.008369 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001406 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001906 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005150 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001648 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.016555 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.007546 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000996 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.045509 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.003289 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001204 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.034883 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.019977 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001711 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001596 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001261 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.011418 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001791 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.022675 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001424 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001395 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001676 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001313 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.016838 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003274 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.014985 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002490 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.015061 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001409 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043585

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 13699, number of negative: 4825
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000463 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 18524, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739527 -> initscore=1.043512
[LightGBM] [Info] Start training from score 1.043512

Best XGBoost params: {'classifier__colsample_bytree': 0.8, 'classifier__learning_rate': 0.05, 'classifier__max_depth': 7, 'classifier__n_estimators': 200, 'classifier__subsample': 0.7}
Best XGBoost score: 0.9702549091619229

Best LightGBM params: {'classifier__colsample_bytree': 0.7, 'classifier__learning_rate': 0.05, 'classifier__n_estimators': 300, 'classifier__num_leaves': 20, 'classifier__subsample': 0.7}
Best LightGBM score: 0.9699849890551265

In [30]:
print('Catboost optimizing')
grid_search_catboost = GridSearchCV(catboost_pipeline,param_grid=param_grid_catboost, cv=cv, scoring='accuracy', n_jobs=-1, verbose=1)
grid_search_catboost.fit(X,y)

Catboost optimizing
Fitting 5 folds for each of 12 candidates, totalling 60 fits
0:	learn: 0.6763690	total: 61.1ms	remaining: 12.2s
0:	learn: 0.6767120	total: 61ms	remaining: 12.1s
0:	learn: 0.6146117	total: 60.9ms	remaining: 12.1s
0:	learn: 0.6122698	total: 59.6ms	remaining: 11.9s
0:	learn: 0.6766920	total: 59.4ms	remaining: 11.8s
1:	learn: 0.6604016	total: 65.3ms	remaining: 6.46s
1:	learn: 0.5457391	total: 65.2ms	remaining: 6.45s
1:	learn: 0.5443252	total: 64ms	remaining: 6.34s
1:	learn: 0.6606633	total: 64.8ms	remaining: 6.42s
1:	learn: 0.6601231	total: 67.7ms	remaining: 6.7s
2:	learn: 0.4852233	total: 68.6ms	remaining: 4.51s
2:	learn: 0.6448056	total: 69.5ms	remaining: 4.57s
2:	learn: 0.4861429	total: 68.8ms	remaining: 4.52s
2:	learn: 0.6453399	total: 68.7ms	remaining: 4.51s
2:	learn: 0.6443848	total: 72.5ms	remaining: 4.76s
3:	learn: 0.4354816	total: 72.4ms	remaining: 3.55s
3:	learn: 0.6305730	total: 71.4ms	remaining: 3.5s
3:	learn: 0.6294289	total: 74ms	remaining: 3.63s
3:	learn: 0.4365895	total: 72.9ms	remaining: 3.57s
0:	learn: 0.6124611	total: 56.1ms	remaining: 11.2s
4:	learn: 0.3933478	total: 76.7ms	remaining: 2.99s
4:	learn: 0.6161061	total: 75.3ms	remaining: 2.94s
3:	learn: 0.6292235	total: 77.5ms	remaining: 3.8s
4:	learn: 0.3936546	total: 77.6ms	remaining: 3.03s
4:	learn: 0.6148932	total: 79.4ms	remaining: 3.1s
5:	learn: 0.3589398	total: 79.4ms	remaining: 2.57s
1:	learn: 0.5435416	total: 61.6ms	remaining: 6.1s
4:	learn: 0.6145557	total: 82.2ms	remaining: 3.21s
6:	learn: 0.3279806	total: 84.5ms	remaining: 2.33s
5:	learn: 0.6022321	total: 83.5ms	remaining: 2.7s
0:	learn: 0.6763375	total: 61.6ms	remaining: 12.3s
5:	learn: 0.6005603	total: 83.4ms	remaining: 2.7s
2:	learn: 0.4849874	total: 66.9ms	remaining: 4.4s
5:	learn: 0.3585143	total: 83.7ms	remaining: 2.71s
5:	learn: 0.6004035	total: 86.4ms	remaining: 2.79s
0:	learn: 0.6768367	total: 59.7ms	remaining: 11.9s
1:	learn: 0.6603075	total: 64.5ms	remaining: 6.39s
7:	learn: 0.3017079	total: 89ms	remaining: 2.13s
3:	learn: 0.4342327	total: 71.1ms	remaining: 3.48s
6:	learn: 0.5886656	total: 88.6ms	remaining: 2.44s
2:	learn: 0.6447101	total: 67.4ms	remaining: 4.43s
1:	learn: 0.6606491	total: 62.9ms	remaining: 6.23s
8:	learn: 0.2794224	total: 92ms	remaining: 1.95s
6:	learn: 0.5865584	total: 93.1ms	remaining: 2.57s
4:	learn: 0.3921013	total: 74.1ms	remaining: 2.89s
6:	learn: 0.5867641	total: 91.1ms	remaining: 2.51s
6:	learn: 0.3272303	total: 91.3ms	remaining: 2.52s
3:	learn: 0.6296341	total: 70.7ms	remaining: 3.46s
2:	learn: 0.6450503	total: 66.7ms	remaining: 4.38s
9:	learn: 0.2612751	total: 94.6ms	remaining: 1.8s
5:	learn: 0.3556647	total: 76.8ms	remaining: 2.48s
7:	learn: 0.5751602	total: 95.7ms	remaining: 2.3s
4:	learn: 0.6148092	total: 73.9ms	remaining: 2.88s
7:	learn: 0.5728585	total: 98.3ms	remaining: 2.36s
3:	learn: 0.6296710	total: 70.5ms	remaining: 3.45s
7:	learn: 0.5732677	total: 96.4ms	remaining: 2.31s
10:	learn: 0.2435316	total: 99.1ms	remaining: 1.7s
7:	learn: 0.3004268	total: 97.5ms	remaining: 2.34s
5:	learn: 0.6002280	total: 77.2ms	remaining: 2.5s
8:	learn: 0.5622912	total: 99.2ms	remaining: 2.1s
4:	learn: 0.6151002	total: 73.6ms	remaining: 2.87s
11:	learn: 0.2286360	total: 102ms	remaining: 1.6s
8:	learn: 0.5602061	total: 101ms	remaining: 2.14s
8:	learn: 0.5596719	total: 104ms	remaining: 2.21s
8:	learn: 0.2776794	total: 102ms	remaining: 2.17s
5:	learn: 0.6007471	total: 77ms	remaining: 2.49s
6:	learn: 0.3250960	total: 86.9ms	remaining: 2.39s
12:	learn: 0.2165319	total: 105ms	remaining: 1.51s
9:	learn: 0.5470620	total: 107ms	remaining: 2.03s
9:	learn: 0.5497852	total: 105ms	remaining: 2s
9:	learn: 0.2576101	total: 105ms	remaining: 2s
6:	learn: 0.5861778	total: 84.4ms	remaining: 2.33s
9:	learn: 0.5478269	total: 107ms	remaining: 2.03s
10:	learn: 0.5349988	total: 110ms	remaining: 1.89s
6:	learn: 0.5870011	total: 81.5ms	remaining: 2.25s
13:	learn: 0.2060948	total: 110ms	remaining: 1.46s
10:	learn: 0.5379648	total: 109ms	remaining: 1.87s
7:	learn: 0.2985695	total: 91.9ms	remaining: 2.21s
7:	learn: 0.5728418	total: 89.9ms	remaining: 2.16s
10:	learn: 0.2409793	total: 112ms	remaining: 1.93s
11:	learn: 0.5229259	total: 115ms	remaining: 1.8s
10:	learn: 0.5356453	total: 112ms	remaining: 1.93s
11:	learn: 0.5262375	total: 113ms	remaining: 1.77s
7:	learn: 0.5737183	total: 86.5ms	remaining: 2.08s
8:	learn: 0.2757035	total: 96.3ms	remaining: 2.04s
8:	learn: 0.5598325	total: 93.1ms	remaining: 1.98s
14:	learn: 0.1968697	total: 117ms	remaining: 1.44s
9:	learn: 0.2562302	total: 99.3ms	remaining: 1.89s
11:	learn: 0.2259232	total: 116ms	remaining: 1.82s
11:	learn: 0.5237144	total: 117ms	remaining: 1.83s
8:	learn: 0.5604695	total: 91.1ms	remaining: 1.93s
9:	learn: 0.5471797	total: 96.3ms	remaining: 1.83s
15:	learn: 0.1885267	total: 120ms	remaining: 1.38s
12:	learn: 0.5110093	total: 121ms	remaining: 1.75s
12:	learn: 0.5149728	total: 119ms	remaining: 1.72s
12:	learn: 0.2131489	total: 120ms	remaining: 1.73s
10:	learn: 0.2392293	total: 104ms	remaining: 1.79s
12:	learn: 0.5125622	total: 121ms	remaining: 1.74s
9:	learn: 0.5477731	total: 95.8ms	remaining: 1.82s
10:	learn: 0.5349928	total: 101ms	remaining: 1.73s
11:	learn: 0.2250007	total: 107ms	remaining: 1.67s
13:	learn: 0.4994962	total: 126ms	remaining: 1.68s
13:	learn: 0.5038316	total: 124ms	remaining: 1.65s
16:	learn: 0.1813582	total: 127ms	remaining: 1.37s
13:	learn: 0.2026968	total: 126ms	remaining: 1.67s
11:	learn: 0.5230204	total: 105ms	remaining: 1.64s
13:	learn: 0.5013594	total: 126ms	remaining: 1.67s
10:	learn: 0.5354843	total: 102ms	remaining: 1.76s
12:	learn: 0.2130489	total: 114ms	remaining: 1.64s
14:	learn: 0.4905587	total: 130ms	remaining: 1.61s
17:	learn: 0.1751439	total: 133ms	remaining: 1.35s
12:	learn: 0.5114859	total: 111ms	remaining: 1.59s
14:	learn: 0.4887540	total: 136ms	remaining: 1.67s
15:	learn: 0.4801551	total: 133ms	remaining: 1.53s
13:	learn: 0.2024308	total: 118ms	remaining: 1.56s
14:	learn: 0.1932248	total: 135ms	remaining: 1.66s
11:	learn: 0.5237301	total: 108ms	remaining: 1.69s
14:	learn: 0.4928951	total: 136ms	remaining: 1.67s
15:	learn: 0.4780648	total: 139ms	remaining: 1.6s
16:	learn: 0.4700366	total: 136ms	remaining: 1.47s
18:	learn: 0.1696942	total: 138ms	remaining: 1.32s
14:	learn: 0.1932085	total: 121ms	remaining: 1.5s
13:	learn: 0.5004106	total: 117ms	remaining: 1.55s
15:	learn: 0.1850377	total: 139ms	remaining: 1.6s
17:	learn: 0.4600569	total: 140ms	remaining: 1.41s
12:	learn: 0.5123783	total: 113ms	remaining: 1.63s
15:	learn: 0.1853166	total: 124ms	remaining: 1.43s
16:	learn: 0.4677915	total: 145ms	remaining: 1.57s
13:	learn: 0.5013719	total: 116ms	remaining: 1.54s
19:	learn: 0.1651182	total: 145ms	remaining: 1.31s
15:	learn: 0.4826699	total: 144ms	remaining: 1.66s
16:	learn: 0.1786508	total: 127ms	remaining: 1.37s
16:	learn: 0.1780944	total: 144ms	remaining: 1.55s
18:	learn: 0.4503501	total: 145ms	remaining: 1.38s
14:	learn: 0.4893675	total: 126ms	remaining: 1.55s
17:	learn: 0.4581357	total: 150ms	remaining: 1.51s
14:	learn: 0.4906229	total: 121ms	remaining: 1.5s
20:	learn: 0.1608591	total: 150ms	remaining: 1.28s
17:	learn: 0.1718681	total: 148ms	remaining: 1.5s
17:	learn: 0.1729430	total: 133ms	remaining: 1.34s
19:	learn: 0.4409225	total: 149ms	remaining: 1.34s
16:	learn: 0.4723878	total: 151ms	remaining: 1.62s
21:	learn: 0.1573162	total: 153ms	remaining: 1.24s
18:	learn: 0.1677348	total: 136ms	remaining: 1.29s
18:	learn: 0.4487542	total: 156ms	remaining: 1.48s
17:	learn: 0.4624395	total: 154ms	remaining: 1.56s
18:	learn: 0.1666795	total: 154ms	remaining: 1.47s
22:	learn: 0.1541334	total: 156ms	remaining: 1.2s
20:	learn: 0.4320293	total: 154ms	remaining: 1.31s
15:	learn: 0.4788959	total: 134ms	remaining: 1.54s
19:	learn: 0.1633079	total: 141ms	remaining: 1.27s
19:	learn: 0.1620929	total: 157ms	remaining: 1.42s
23:	learn: 0.1513006	total: 159ms	remaining: 1.17s
21:	learn: 0.4234034	total: 158ms	remaining: 1.27s
15:	learn: 0.4799684	total: 132ms	remaining: 1.51s
19:	learn: 0.4395862	total: 163ms	remaining: 1.47s
16:	learn: 0.4682547	total: 140ms	remaining: 1.5s
22:	learn: 0.4147536	total: 161ms	remaining: 1.24s
18:	learn: 0.4531256	total: 162ms	remaining: 1.54s
16:	learn: 0.4697703	total: 135ms	remaining: 1.46s
20:	learn: 0.1590932	total: 146ms	remaining: 1.24s
24:	learn: 0.1490458	total: 165ms	remaining: 1.15s
23:	learn: 0.4066078	total: 164ms	remaining: 1.2s
17:	learn: 0.4581327	total: 143ms	remaining: 1.45s
17:	learn: 0.4601392	total: 139ms	remaining: 1.41s
19:	learn: 0.4439406	total: 167ms	remaining: 1.51s
24:	learn: 0.3986479	total: 167ms	remaining: 1.17s
18:	learn: 0.4484690	total: 146ms	remaining: 1.39s
21:	learn: 0.1555260	total: 151ms	remaining: 1.22s
20:	learn: 0.1578877	total: 168ms	remaining: 1.43s
20:	learn: 0.4306537	total: 171ms	remaining: 1.46s
18:	learn: 0.4507844	total: 144ms	remaining: 1.37s
25:	learn: 0.3910795	total: 170ms	remaining: 1.14s
25:	learn: 0.1467798	total: 172ms	remaining: 1.15s
21:	learn: 0.4220240	total: 175ms	remaining: 1.41s
19:	learn: 0.4415823	total: 147ms	remaining: 1.32s
26:	learn: 0.3837655	total: 174ms	remaining: 1.11s
26:	learn: 0.1446816	total: 176ms	remaining: 1.13s
19:	learn: 0.4390791	total: 154ms	remaining: 1.39s
21:	learn: 0.1544757	total: 176ms	remaining: 1.42s
22:	learn: 0.1522848	total: 159ms	remaining: 1.23s
22:	learn: 0.4136363	total: 179ms	remaining: 1.38s
20:	learn: 0.4350471	total: 177ms	remaining: 1.51s
20:	learn: 0.4326604	total: 150ms	remaining: 1.28s
27:	learn: 0.3763357	total: 178ms	remaining: 1.09s
27:	learn: 0.1430131	total: 180ms	remaining: 1.11s
20:	learn: 0.4299557	total: 159ms	remaining: 1.35s
21:	learn: 0.4240218	total: 154ms	remaining: 1.24s
22:	learn: 0.1512039	total: 181ms	remaining: 1.39s
21:	learn: 0.4264383	total: 181ms	remaining: 1.46s
23:	learn: 0.4056262	total: 184ms	remaining: 1.35s
21:	learn: 0.4211321	total: 162ms	remaining: 1.31s
23:	learn: 0.1494686	total: 166ms	remaining: 1.22s
28:	learn: 0.1412919	total: 185ms	remaining: 1.09s
28:	learn: 0.3693803	total: 183ms	remaining: 1.08s
22:	learn: 0.4156425	total: 158ms	remaining: 1.22s
24:	learn: 0.1469542	total: 170ms	remaining: 1.19s
22:	learn: 0.4127210	total: 165ms	remaining: 1.27s
23:	learn: 0.1483725	total: 187ms	remaining: 1.37s
29:	learn: 0.3625005	total: 187ms	remaining: 1.06s
22:	learn: 0.4181015	total: 187ms	remaining: 1.44s
24:	learn: 0.3975357	total: 191ms	remaining: 1.33s
29:	learn: 0.1397911	total: 190ms	remaining: 1.08s
24:	learn: 0.1457490	total: 190ms	remaining: 1.33s
23:	learn: 0.4101320	total: 190ms	remaining: 1.39s
25:	learn: 0.1448051	total: 175ms	remaining: 1.17s
30:	learn: 0.1385379	total: 193ms	remaining: 1.05s
23:	learn: 0.4046488	total: 171ms	remaining: 1.25s
25:	learn: 0.1434987	total: 193ms	remaining: 1.29s
24:	learn: 0.4019424	total: 193ms	remaining: 1.35s
30:	learn: 0.3560603	total: 193ms	remaining: 1.05s
23:	learn: 0.4076477	total: 167ms	remaining: 1.23s
24:	learn: 0.3968181	total: 174ms	remaining: 1.22s
25:	learn: 0.3897379	total: 200ms	remaining: 1.33s
25:	learn: 0.3941699	total: 196ms	remaining: 1.31s
31:	learn: 0.3495673	total: 197ms	remaining: 1.03s
24:	learn: 0.3995998	total: 171ms	remaining: 1.2s
31:	learn: 0.1372876	total: 199ms	remaining: 1.04s
26:	learn: 0.1428792	total: 183ms	remaining: 1.17s
25:	learn: 0.3890035	total: 179ms	remaining: 1.2s
26:	learn: 0.1415308	total: 200ms	remaining: 1.28s
26:	learn: 0.3867299	total: 200ms	remaining: 1.28s
26:	learn: 0.3822870	total: 203ms	remaining: 1.3s
25:	learn: 0.3918398	total: 174ms	remaining: 1.16s
32:	learn: 0.1364199	total: 203ms	remaining: 1.03s
27:	learn: 0.1396922	total: 203ms	remaining: 1.25s
27:	learn: 0.3751395	total: 206ms	remaining: 1.27s
26:	learn: 0.3842472	total: 177ms	remaining: 1.13s
33:	learn: 0.1354419	total: 207ms	remaining: 1.01s
28:	learn: 0.1381201	total: 206ms	remaining: 1.21s
28:	learn: 0.3679525	total: 209ms	remaining: 1.23s
27:	learn: 0.1410349	total: 190ms	remaining: 1.17s
27:	learn: 0.3767687	total: 180ms	remaining: 1.11s
26:	learn: 0.3815118	total: 185ms	remaining: 1.19s
32:	learn: 0.3435128	total: 207ms	remaining: 1.05s
29:	learn: 0.1366553	total: 209ms	remaining: 1.18s
27:	learn: 0.3794082	total: 208ms	remaining: 1.28s
34:	learn: 0.1346644	total: 211ms	remaining: 997ms
27:	learn: 0.3741937	total: 189ms	remaining: 1.16s
28:	learn: 0.3697757	total: 185ms	remaining: 1.09s
28:	learn: 0.3724685	total: 212ms	remaining: 1.25s
28:	learn: 0.3670968	total: 192ms	remaining: 1.13s
28:	learn: 0.1395479	total: 197ms	remaining: 1.16s
35:	learn: 0.1338527	total: 216ms	remaining: 983ms
29:	learn: 0.3612316	total: 218ms	remaining: 1.23s
30:	learn: 0.1354162	total: 215ms	remaining: 1.17s
33:	learn: 0.3374743	total: 215ms	remaining: 1.05s
29:	learn: 0.3602715	total: 195ms	remaining: 1.1s
29:	learn: 0.3657385	total: 215ms	remaining: 1.22s
29:	learn: 0.3630461	total: 191ms	remaining: 1.08s
36:	learn: 0.1331577	total: 219ms	remaining: 966ms
30:	learn: 0.3535688	total: 197ms	remaining: 1.07s
30:	learn: 0.3590903	total: 218ms	remaining: 1.19s
31:	learn: 0.3524062	total: 221ms	remaining: 1.16s
37:	learn: 0.1325380	total: 222ms	remaining: 948ms
31:	learn: 0.3474439	total: 201ms	remaining: 1.05s
29:	learn: 0.1381157	total: 208ms	remaining: 1.18s
32:	learn: 0.3461118	total: 224ms	remaining: 1.13s
30:	learn: 0.3564400	total: 198ms	remaining: 1.08s
34:	learn: 0.3316771	total: 225ms	remaining: 1.06s
38:	learn: 0.1319735	total: 227ms	remaining: 937ms
31:	learn: 0.1342532	total: 227ms	remaining: 1.19s
33:	learn: 0.3403010	total: 227ms	remaining: 1.11s
30:	learn: 0.3545491	total: 228ms	remaining: 1.24s
32:	learn: 0.3411284	total: 208ms	remaining: 1.05s
30:	learn: 0.1368301	total: 213ms	remaining: 1.16s
39:	learn: 0.1314352	total: 232ms	remaining: 928ms
34:	learn: 0.3346046	total: 231ms	remaining: 1.09s
31:	learn: 0.3500571	total: 205ms	remaining: 1.08s
35:	learn: 0.3261819	total: 233ms	remaining: 1.06s
31:	learn: 0.3480268	total: 235ms	remaining: 1.24s
40:	learn: 0.1310021	total: 236ms	remaining: 915ms
35:	learn: 0.3289881	total: 235ms	remaining: 1.07s
32:	learn: 0.1330505	total: 238ms	remaining: 1.2s
36:	learn: 0.3236072	total: 237ms	remaining: 1.04s
31:	learn: 0.1356350	total: 223ms	remaining: 1.17s
41:	learn: 0.1305788	total: 241ms	remaining: 907ms
37:	learn: 0.3183598	total: 241ms	remaining: 1.03s
36:	learn: 0.3205693	total: 241ms	remaining: 1.06s
33:	learn: 0.3351785	total: 221ms	remaining: 1.08s
32:	learn: 0.3417264	total: 244ms	remaining: 1.23s
32:	learn: 0.3438658	total: 219ms	remaining: 1.11s
33:	learn: 0.1321247	total: 247ms	remaining: 1.2s
37:	learn: 0.3151967	total: 246ms	remaining: 1.05s
32:	learn: 0.1345652	total: 231ms	remaining: 1.17s
34:	learn: 0.3292608	total: 227ms	remaining: 1.07s
33:	learn: 0.3378250	total: 223ms	remaining: 1.09s
33:	learn: 0.3356521	total: 250ms	remaining: 1.22s
38:	learn: 0.3105196	total: 249ms	remaining: 1.02s
42:	learn: 0.1301777	total: 252ms	remaining: 919ms
34:	learn: 0.1312455	total: 251ms	remaining: 1.18s
34:	learn: 0.3320126	total: 226ms	remaining: 1.06s
39:	learn: 0.3054149	total: 252ms	remaining: 1.01s
33:	learn: 0.1335100	total: 237ms	remaining: 1.15s
35:	learn: 0.3236329	total: 232ms	remaining: 1.06s
35:	learn: 0.3262977	total: 229ms	remaining: 1.04s
34:	learn: 0.3298253	total: 256ms	remaining: 1.21s
40:	learn: 0.3006962	total: 255ms	remaining: 987ms
35:	learn: 0.1304826	total: 256ms	remaining: 1.17s
43:	learn: 0.1298062	total: 257ms	remaining: 911ms
34:	learn: 0.1327556	total: 241ms	remaining: 1.14s
41:	learn: 0.2959947	total: 258ms	remaining: 969ms
38:	learn: 0.3132719	total: 259ms	remaining: 1.07s
36:	learn: 0.3182805	total: 238ms	remaining: 1.05s
36:	learn: 0.3207653	total: 233ms	remaining: 1.03s
36:	learn: 0.1298136	total: 260ms	remaining: 1.15s
35:	learn: 0.3240846	total: 261ms	remaining: 1.19s
37:	learn: 0.3155351	total: 236ms	remaining: 1.01s
37:	learn: 0.3129799	total: 241ms	remaining: 1.03s
35:	learn: 0.1319696	total: 248ms	remaining: 1.13s
44:	learn: 0.1294303	total: 265ms	remaining: 913ms
37:	learn: 0.1290834	total: 264ms	remaining: 1.13s
42:	learn: 0.2913945	total: 263ms	remaining: 962ms
39:	learn: 0.3081308	total: 265ms	remaining: 1.06s
38:	learn: 0.3077198	total: 244ms	remaining: 1.01s
38:	learn: 0.3103498	total: 240ms	remaining: 992ms
36:	learn: 0.3185562	total: 267ms	remaining: 1.18s
38:	learn: 0.1285322	total: 269ms	remaining: 1.11s
45:	learn: 0.1290892	total: 270ms	remaining: 903ms
39:	learn: 0.3026295	total: 248ms	remaining: 992ms
43:	learn: 0.2869207	total: 270ms	remaining: 957ms
46:	learn: 0.1287479	total: 273ms	remaining: 888ms
39:	learn: 0.3052486	total: 246ms	remaining: 984ms
36:	learn: 0.1311711	total: 256ms	remaining: 1.13s
40:	learn: 0.3032067	total: 273ms	remaining: 1.06s
44:	learn: 0.2826310	total: 274ms	remaining: 943ms
39:	learn: 0.1279863	total: 276ms	remaining: 1.1s
47:	learn: 0.1284682	total: 276ms	remaining: 875ms
40:	learn: 0.2977972	total: 256ms	remaining: 991ms
37:	learn: 0.3134276	total: 278ms	remaining: 1.19s
40:	learn: 0.3005744	total: 252ms	remaining: 979ms
41:	learn: 0.2985227	total: 278ms	remaining: 1.05s
37:	learn: 0.1304227	total: 264ms	remaining: 1.13s
40:	learn: 0.1275432	total: 281ms	remaining: 1.09s
48:	learn: 0.1281686	total: 282ms	remaining: 870ms
38:	learn: 0.3082936	total: 283ms	remaining: 1.17s
42:	learn: 0.2939120	total: 283ms	remaining: 1.03s
45:	learn: 0.2784385	total: 283ms	remaining: 948ms
38:	learn: 0.1297263	total: 269ms	remaining: 1.11s
41:	learn: 0.2959692	total: 259ms	remaining: 974ms
41:	learn: 0.1270511	total: 286ms	remaining: 1.08s
39:	learn: 0.3032516	total: 287ms	remaining: 1.15s
41:	learn: 0.2930638	total: 267ms	remaining: 1s
49:	learn: 0.1279197	total: 289ms	remaining: 866ms
40:	learn: 0.2983263	total: 290ms	remaining: 1.13s
46:	learn: 0.2744603	total: 289ms	remaining: 939ms
42:	learn: 0.1266521	total: 290ms	remaining: 1.06s
39:	learn: 0.1291699	total: 274ms	remaining: 1.1s
43:	learn: 0.2897291	total: 290ms	remaining: 1.03s
42:	learn: 0.2914788	total: 265ms	remaining: 967ms
47:	learn: 0.2704881	total: 291ms	remaining: 923ms
42:	learn: 0.2887794	total: 273ms	remaining: 996ms
43:	learn: 0.1262788	total: 294ms	remaining: 1.04s
40:	learn: 0.1285600	total: 278ms	remaining: 1.08s
50:	learn: 0.1277143	total: 295ms	remaining: 863ms
41:	learn: 0.2937670	total: 296ms	remaining: 1.11s
48:	learn: 0.2666829	total: 294ms	remaining: 907ms
44:	learn: 0.2854495	total: 297ms	remaining: 1.02s
51:	learn: 0.1274745	total: 299ms	remaining: 850ms
43:	learn: 0.2870429	total: 272ms	remaining: 963ms
49:	learn: 0.2630253	total: 297ms	remaining: 892ms
43:	learn: 0.2842542	total: 278ms	remaining: 987ms
44:	learn: 0.1259512	total: 300ms	remaining: 1.03s
41:	learn: 0.1281280	total: 284ms	remaining: 1.07s
52:	learn: 0.1272560	total: 302ms	remaining: 838ms
44:	learn: 0.2830640	total: 276ms	remaining: 950ms
44:	learn: 0.2799342	total: 282ms	remaining: 971ms
42:	learn: 0.1276353	total: 287ms	remaining: 1.05s
45:	learn: 0.2812925	total: 303ms	remaining: 1.01s
42:	learn: 0.2891300	total: 305ms	remaining: 1.11s
50:	learn: 0.2595120	total: 304ms	remaining: 888ms
45:	learn: 0.1256733	total: 306ms	remaining: 1.02s
45:	learn: 0.2758201	total: 286ms	remaining: 958ms
53:	learn: 0.1270787	total: 308ms	remaining: 833ms
45:	learn: 0.2789451	total: 281ms	remaining: 942ms
43:	learn: 0.1271824	total: 292ms	remaining: 1.03s
51:	learn: 0.2558331	total: 307ms	remaining: 873ms
43:	learn: 0.2847510	total: 309ms	remaining: 1.1s
46:	learn: 0.2772499	total: 308ms	remaining: 1s
46:	learn: 0.1253640	total: 311ms	remaining: 1.01s
52:	learn: 0.2524691	total: 311ms	remaining: 863ms
44:	learn: 0.1268222	total: 296ms	remaining: 1.02s
54:	learn: 0.1269231	total: 313ms	remaining: 826ms
46:	learn: 0.2716744	total: 292ms	remaining: 950ms
46:	learn: 0.2749370	total: 287ms	remaining: 935ms
44:	learn: 0.2803738	total: 315ms	remaining: 1.08s
47:	learn: 0.1250004	total: 315ms	remaining: 998ms
47:	learn: 0.2732619	total: 315ms	remaining: 998ms
47:	learn: 0.2710957	total: 290ms	remaining: 918ms
47:	learn: 0.2677897	total: 296ms	remaining: 937ms
53:	learn: 0.2492524	total: 316ms	remaining: 854ms

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('num',
                                                                         Pipeline(steps=[('imputer',
                                                                                          SimpleImputer())]),
                                                                         Index(['Time_spent_Alone', 'Social_event_attendance', 'Going_outside',
       'Friends_circle_size', 'Post_frequency', 'match_p_is_null'],...
                                                                                          OrdinalEncoder(handle_unknown='use_encoded_value',
                                                                                                         unknown_value=-1))]),
                                                                         Index(['Stage_fear', 'Drained_after_socializing', 'match_p'], dtype='object'))])),
                                       ('classifier',
                                        <catboost.core.CatBoostClassifier object at 0x1450c5e90>)]),
             n_jobs=-1,
             param_grid={'classifier__depth': [4, 6, 8],
                         'classifier__iterations': [200, 300],
                         'classifier__learning_rate': [0.01, 0.05]},
             scoring='accuracy', verbose=1)

In [32]:
best_xgb = grid_search_xgb.best_estimator_
best_lgbm = grid_search_lgbm.best_estimator_
best_catboost = grid_search_catboost.best_estimator_
xgb_weight = grid_search_xgb.best_score_
lgbm_weight = grid_search_lgbm.best_score_
catboost_weight = grid_search_catboost.best_score_

ensemble = VotingClassifier(
    estimators=[
        ('xgb', best_xgb),
        ('lgbm', best_lgbm),
        ('catboost', best_catboost)
    ],
    voting='soft', 
    weights=[xgb_weight, lgbm_weight, catboost_weight],  
    n_jobs=-1
)

print("\nTraining ensemble model...")
ensemble.fit(X, y)

Training ensemble model...
0:	learn: 0.6129472	total: 2.79ms	remaining: 835ms
1:	learn: 0.5456588	total: 5.55ms	remaining: 828ms
2:	learn: 0.4866700	total: 8.01ms	remaining: 793ms
3:	learn: 0.4376015	total: 10.1ms	remaining: 748ms
4:	learn: 0.3952016	total: 12.4ms	remaining: 734ms
5:	learn: 0.3603733	total: 14.3ms	remaining: 703ms
6:	learn: 0.3295251	total: 16.4ms	remaining: 687ms
7:	learn: 0.3023780	total: 18.3ms	remaining: 667ms
8:	learn: 0.2792319	total: 20.6ms	remaining: 667ms
9:	learn: 0.2593210	total: 22.8ms	remaining: 661ms
10:	learn: 0.2425994	total: 24.9ms	remaining: 654ms
11:	learn: 0.2278393	total: 27.1ms	remaining: 651ms
12:	learn: 0.2157283	total: 29.3ms	remaining: 647ms
13:	learn: 0.2047842	total: 31.3ms	remaining: 639ms
14:	learn: 0.1957355	total: 33.7ms	remaining: 641ms
15:	learn: 0.1875274	total: 35.9ms	remaining: 638ms
16:	learn: 0.1804807	total: 38.2ms	remaining: 636ms
17:	learn: 0.1745573	total: 40.5ms	remaining: 634ms
18:	learn: 0.1690005	total: 42.5ms	remaining: 629ms
19:	learn: 0.1642765	total: 44.9ms	remaining: 628ms
20:	learn: 0.1603960	total: 47.2ms	remaining: 627ms
21:	learn: 0.1566327	total: 49.4ms	remaining: 624ms
22:	learn: 0.1535230	total: 51.6ms	remaining: 621ms
23:	learn: 0.1506689	total: 53.8ms	remaining: 619ms
24:	learn: 0.1479759	total: 56.1ms	remaining: 618ms
25:	learn: 0.1457988	total: 58.4ms	remaining: 616ms
26:	learn: 0.1438354	total: 60.7ms	remaining: 614ms
27:	learn: 0.1419939	total: 62.8ms	remaining: 610ms
28:	learn: 0.1403578	total: 65.1ms	remaining: 608ms
29:	learn: 0.1388461	total: 67.5ms	remaining: 608ms
30:	learn: 0.1375668	total: 69.8ms	remaining: 606ms
31:	learn: 0.1364247	total: 72.2ms	remaining: 605ms
32:	learn: 0.1353447	total: 74.4ms	remaining: 602ms
33:	learn: 0.1343182	total: 76.9ms	remaining: 601ms
34:	learn: 0.1333612	total: 79.7ms	remaining: 603ms
35:	learn: 0.1325396	total: 81.8ms	remaining: 600ms

/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:29:02] WARNING: /Users/runner/work/xgboost/xgboost/src/context.cc:203: XGBoost is not compiled with CUDA support.
  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:29:02] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

36:	learn: 0.1318813	total: 84.7ms	remaining: 602ms
37:	learn: 0.1311955	total: 87.4ms	remaining: 603ms
38:	learn: 0.1306532	total: 90.2ms	remaining: 604ms
39:	learn: 0.1300934	total: 92.2ms	remaining: 600ms
40:	learn: 0.1296092	total: 95.6ms	remaining: 604ms
41:	learn: 0.1291060	total: 98.4ms	remaining: 604ms
42:	learn: 0.1287363	total: 101ms	remaining: 603ms
43:	learn: 0.1283366	total: 103ms	remaining: 601ms
44:	learn: 0.1279593	total: 106ms	remaining: 599ms
45:	learn: 0.1276546	total: 108ms	remaining: 598ms
46:	learn: 0.1273858	total: 111ms	remaining: 600ms
47:	learn: 0.1271681	total: 114ms	remaining: 599ms
48:	learn: 0.1269419	total: 117ms	remaining: 597ms
49:	learn: 0.1267283	total: 119ms	remaining: 595ms
50:	learn: 0.1265428	total: 121ms	remaining: 592ms
[LightGBM] [Info] Number of positive: 13699, number of negative: 4825
51:	learn: 0.1263684	total: 124ms	remaining: 590ms
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001248 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 18524, number of used features: 9
52:	learn: 0.1261922	total: 126ms	remaining: 588ms
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739527 -> initscore=1.043512
[LightGBM] [Info] Start training from score 1.043512
53:	learn: 0.1259974	total: 130ms	remaining: 591ms
54:	learn: 0.1258232	total: 133ms	remaining: 593ms
55:	learn: 0.1256453	total: 136ms	remaining: 592ms
56:	learn: 0.1255118	total: 139ms	remaining: 592ms
57:	learn: 0.1254011	total: 142ms	remaining: 593ms
58:	learn: 0.1252967	total: 145ms	remaining: 591ms
59:	learn: 0.1251566	total: 147ms	remaining: 589ms
60:	learn: 0.1250407	total: 150ms	remaining: 589ms
61:	learn: 0.1248832	total: 153ms	remaining: 588ms
62:	learn: 0.1247249	total: 156ms	remaining: 586ms
63:	learn: 0.1246255	total: 158ms	remaining: 584ms
64:	learn: 0.1245315	total: 161ms	remaining: 583ms
65:	learn: 0.1244648	total: 164ms	remaining: 582ms
66:	learn: 0.1243995	total: 167ms	remaining: 579ms
67:	learn: 0.1243444	total: 169ms	remaining: 578ms
68:	learn: 0.1242370	total: 172ms	remaining: 576ms
69:	learn: 0.1241477	total: 174ms	remaining: 573ms
70:	learn: 0.1240751	total: 178ms	remaining: 573ms
71:	learn: 0.1239889	total: 181ms	remaining: 572ms
72:	learn: 0.1238908	total: 184ms	remaining: 573ms
73:	learn: 0.1237767	total: 187ms	remaining: 572ms
74:	learn: 0.1237103	total: 191ms	remaining: 573ms
75:	learn: 0.1235964	total: 194ms	remaining: 571ms
76:	learn: 0.1235337	total: 197ms	remaining: 570ms
77:	learn: 0.1234508	total: 199ms	remaining: 568ms
78:	learn: 0.1233840	total: 202ms	remaining: 565ms
79:	learn: 0.1232964	total: 205ms	remaining: 563ms
80:	learn: 0.1232363	total: 207ms	remaining: 560ms
81:	learn: 0.1231752	total: 210ms	remaining: 559ms
82:	learn: 0.1231077	total: 212ms	remaining: 556ms
83:	learn: 0.1230447	total: 215ms	remaining: 552ms
84:	learn: 0.1230042	total: 217ms	remaining: 550ms
85:	learn: 0.1229493	total: 220ms	remaining: 547ms
86:	learn: 0.1228864	total: 222ms	remaining: 544ms
87:	learn: 0.1228109	total: 225ms	remaining: 542ms
88:	learn: 0.1227694	total: 228ms	remaining: 541ms
89:	learn: 0.1226805	total: 231ms	remaining: 539ms
90:	learn: 0.1226109	total: 234ms	remaining: 536ms
91:	learn: 0.1225432	total: 236ms	remaining: 534ms
92:	learn: 0.1225080	total: 239ms	remaining: 532ms
93:	learn: 0.1224630	total: 242ms	remaining: 530ms
94:	learn: 0.1224142	total: 245ms	remaining: 528ms
95:	learn: 0.1223718	total: 247ms	remaining: 525ms
96:	learn: 0.1223405	total: 250ms	remaining: 522ms
97:	learn: 0.1222762	total: 252ms	remaining: 519ms
98:	learn: 0.1222201	total: 255ms	remaining: 517ms
99:	learn: 0.1221493	total: 258ms	remaining: 515ms
100:	learn: 0.1221099	total: 260ms	remaining: 513ms
101:	learn: 0.1220647	total: 263ms	remaining: 510ms
102:	learn: 0.1220141	total: 265ms	remaining: 507ms
103:	learn: 0.1219795	total: 268ms	remaining: 505ms
104:	learn: 0.1219407	total: 270ms	remaining: 502ms
105:	learn: 0.1218964	total: 273ms	remaining: 500ms
106:	learn: 0.1218616	total: 276ms	remaining: 498ms
107:	learn: 0.1218258	total: 279ms	remaining: 495ms
108:	learn: 0.1217804	total: 281ms	remaining: 493ms
109:	learn: 0.1217417	total: 284ms	remaining: 491ms
110:	learn: 0.1216640	total: 287ms	remaining: 489ms
111:	learn: 0.1216177	total: 289ms	remaining: 486ms
112:	learn: 0.1215750	total: 292ms	remaining: 484ms
113:	learn: 0.1215351	total: 296ms	remaining: 483ms
114:	learn: 0.1214729	total: 299ms	remaining: 481ms
115:	learn: 0.1214334	total: 302ms	remaining: 479ms
116:	learn: 0.1213966	total: 304ms	remaining: 476ms
117:	learn: 0.1213657	total: 307ms	remaining: 474ms
118:	learn: 0.1213393	total: 311ms	remaining: 473ms
119:	learn: 0.1213144	total: 313ms	remaining: 470ms
120:	learn: 0.1212772	total: 316ms	remaining: 467ms
121:	learn: 0.1212343	total: 318ms	remaining: 464ms
122:	learn: 0.1212080	total: 321ms	remaining: 461ms
123:	learn: 0.1211772	total: 324ms	remaining: 459ms
124:	learn: 0.1211490	total: 326ms	remaining: 457ms
125:	learn: 0.1211074	total: 329ms	remaining: 454ms
126:	learn: 0.1210772	total: 332ms	remaining: 452ms
127:	learn: 0.1210496	total: 334ms	remaining: 449ms
128:	learn: 0.1210041	total: 336ms	remaining: 446ms
129:	learn: 0.1209772	total: 339ms	remaining: 443ms
130:	learn: 0.1209514	total: 342ms	remaining: 441ms
131:	learn: 0.1209200	total: 345ms	remaining: 439ms
132:	learn: 0.1208837	total: 347ms	remaining: 436ms
133:	learn: 0.1208390	total: 350ms	remaining: 434ms
134:	learn: 0.1207931	total: 353ms	remaining: 431ms
135:	learn: 0.1207654	total: 355ms	remaining: 428ms
136:	learn: 0.1207203	total: 358ms	remaining: 426ms
137:	learn: 0.1207071	total: 360ms	remaining: 423ms
138:	learn: 0.1206463	total: 363ms	remaining: 420ms
139:	learn: 0.1206225	total: 365ms	remaining: 418ms
140:	learn: 0.1206003	total: 368ms	remaining: 415ms
141:	learn: 0.1205624	total: 370ms	remaining: 412ms
142:	learn: 0.1205475	total: 373ms	remaining: 409ms
143:	learn: 0.1205039	total: 375ms	remaining: 407ms
144:	learn: 0.1204722	total: 378ms	remaining: 404ms
145:	learn: 0.1204344	total: 381ms	remaining: 402ms
146:	learn: 0.1203770	total: 384ms	remaining: 399ms
147:	learn: 0.1203439	total: 386ms	remaining: 397ms
148:	learn: 0.1203095	total: 389ms	remaining: 394ms
149:	learn: 0.1202973	total: 391ms	remaining: 391ms
150:	learn: 0.1202577	total: 394ms	remaining: 389ms
151:	learn: 0.1202314	total: 397ms	remaining: 386ms
152:	learn: 0.1202057	total: 399ms	remaining: 384ms
153:	learn: 0.1201588	total: 402ms	remaining: 381ms
154:	learn: 0.1201404	total: 404ms	remaining: 378ms
155:	learn: 0.1201092	total: 407ms	remaining: 376ms
156:	learn: 0.1200601	total: 410ms	remaining: 373ms
157:	learn: 0.1200256	total: 412ms	remaining: 370ms
158:	learn: 0.1199264	total: 415ms	remaining: 368ms
159:	learn: 0.1198920	total: 417ms	remaining: 365ms
160:	learn: 0.1198678	total: 420ms	remaining: 363ms
161:	learn: 0.1198313	total: 423ms	remaining: 360ms
162:	learn: 0.1197992	total: 425ms	remaining: 357ms
163:	learn: 0.1197633	total: 428ms	remaining: 355ms
164:	learn: 0.1196901	total: 430ms	remaining: 352ms
165:	learn: 0.1196533	total: 433ms	remaining: 349ms
166:	learn: 0.1196148	total: 435ms	remaining: 347ms
167:	learn: 0.1195673	total: 438ms	remaining: 344ms
168:	learn: 0.1195462	total: 440ms	remaining: 341ms
169:	learn: 0.1195160	total: 443ms	remaining: 339ms
170:	learn: 0.1194755	total: 446ms	remaining: 336ms
171:	learn: 0.1194511	total: 448ms	remaining: 334ms
172:	learn: 0.1194278	total: 451ms	remaining: 331ms
173:	learn: 0.1193773	total: 454ms	remaining: 329ms
174:	learn: 0.1193339	total: 456ms	remaining: 326ms
175:	learn: 0.1193104	total: 459ms	remaining: 323ms
176:	learn: 0.1192632	total: 462ms	remaining: 321ms
177:	learn: 0.1192242	total: 464ms	remaining: 318ms
178:	learn: 0.1192089	total: 466ms	remaining: 315ms
179:	learn: 0.1191814	total: 469ms	remaining: 313ms
180:	learn: 0.1191559	total: 472ms	remaining: 310ms
181:	learn: 0.1191206	total: 474ms	remaining: 307ms
182:	learn: 0.1190997	total: 477ms	remaining: 305ms
183:	learn: 0.1190608	total: 479ms	remaining: 302ms
184:	learn: 0.1190257	total: 482ms	remaining: 300ms
185:	learn: 0.1189858	total: 485ms	remaining: 297ms
186:	learn: 0.1189472	total: 488ms	remaining: 295ms
187:	learn: 0.1189150	total: 490ms	remaining: 292ms
188:	learn: 0.1188785	total: 493ms	remaining: 290ms
189:	learn: 0.1188431	total: 496ms	remaining: 287ms
190:	learn: 0.1188187	total: 498ms	remaining: 284ms
191:	learn: 0.1187886	total: 501ms	remaining: 282ms
192:	learn: 0.1187640	total: 504ms	remaining: 279ms
193:	learn: 0.1187431	total: 507ms	remaining: 277ms
194:	learn: 0.1187107	total: 510ms	remaining: 274ms
195:	learn: 0.1186883	total: 512ms	remaining: 272ms
196:	learn: 0.1186530	total: 515ms	remaining: 269ms
197:	learn: 0.1186242	total: 517ms	remaining: 266ms
198:	learn: 0.1185983	total: 520ms	remaining: 264ms
199:	learn: 0.1185675	total: 522ms	remaining: 261ms
200:	learn: 0.1185471	total: 525ms	remaining: 259ms
201:	learn: 0.1185236	total: 527ms	remaining: 256ms
202:	learn: 0.1184927	total: 530ms	remaining: 253ms
203:	learn: 0.1184708	total: 532ms	remaining: 250ms
204:	learn: 0.1184443	total: 534ms	remaining: 248ms
205:	learn: 0.1184189	total: 537ms	remaining: 245ms
206:	learn: 0.1183936	total: 540ms	remaining: 242ms
207:	learn: 0.1183495	total: 543ms	remaining: 240ms
208:	learn: 0.1183295	total: 545ms	remaining: 237ms
209:	learn: 0.1182951	total: 548ms	remaining: 235ms
210:	learn: 0.1182722	total: 550ms	remaining: 232ms
211:	learn: 0.1182389	total: 553ms	remaining: 230ms
212:	learn: 0.1182052	total: 556ms	remaining: 227ms
213:	learn: 0.1181494	total: 559ms	remaining: 224ms
214:	learn: 0.1181217	total: 561ms	remaining: 222ms
215:	learn: 0.1181020	total: 564ms	remaining: 219ms
216:	learn: 0.1180661	total: 567ms	remaining: 217ms
217:	learn: 0.1180476	total: 569ms	remaining: 214ms
218:	learn: 0.1180237	total: 572ms	remaining: 212ms
219:	learn: 0.1180085	total: 575ms	remaining: 209ms
220:	learn: 0.1179920	total: 577ms	remaining: 206ms
221:	learn: 0.1179647	total: 581ms	remaining: 204ms
222:	learn: 0.1179458	total: 583ms	remaining: 201ms
223:	learn: 0.1179168	total: 586ms	remaining: 199ms
224:	learn: 0.1178891	total: 589ms	remaining: 196ms
225:	learn: 0.1178628	total: 592ms	remaining: 194ms
226:	learn: 0.1178381	total: 595ms	remaining: 191ms
227:	learn: 0.1178157	total: 597ms	remaining: 189ms
228:	learn: 0.1177838	total: 600ms	remaining: 186ms
229:	learn: 0.1177616	total: 603ms	remaining: 184ms
230:	learn: 0.1177451	total: 606ms	remaining: 181ms
231:	learn: 0.1177204	total: 609ms	remaining: 178ms
232:	learn: 0.1177048	total: 611ms	remaining: 176ms
233:	learn: 0.1176782	total: 614ms	remaining: 173ms
234:	learn: 0.1176483	total: 616ms	remaining: 170ms
235:	learn: 0.1176359	total: 619ms	remaining: 168ms
236:	learn: 0.1176103	total: 622ms	remaining: 165ms
237:	learn: 0.1175802	total: 625ms	remaining: 163ms
238:	learn: 0.1175595	total: 627ms	remaining: 160ms
239:	learn: 0.1175438	total: 630ms	remaining: 157ms
240:	learn: 0.1175167	total: 632ms	remaining: 155ms
241:	learn: 0.1174766	total: 635ms	remaining: 152ms
242:	learn: 0.1174634	total: 638ms	remaining: 150ms
243:	learn: 0.1174491	total: 640ms	remaining: 147ms
244:	learn: 0.1174314	total: 643ms	remaining: 144ms
245:	learn: 0.1174130	total: 645ms	remaining: 142ms
246:	learn: 0.1173952	total: 648ms	remaining: 139ms
247:	learn: 0.1173550	total: 650ms	remaining: 136ms
248:	learn: 0.1173321	total: 653ms	remaining: 134ms
249:	learn: 0.1172951	total: 656ms	remaining: 131ms
250:	learn: 0.1172781	total: 659ms	remaining: 129ms
251:	learn: 0.1172494	total: 662ms	remaining: 126ms
252:	learn: 0.1172377	total: 664ms	remaining: 123ms
253:	learn: 0.1172033	total: 666ms	remaining: 121ms
254:	learn: 0.1171804	total: 669ms	remaining: 118ms
255:	learn: 0.1171545	total: 672ms	remaining: 115ms
256:	learn: 0.1171330	total: 675ms	remaining: 113ms
257:	learn: 0.1170922	total: 677ms	remaining: 110ms
258:	learn: 0.1170625	total: 680ms	remaining: 108ms
259:	learn: 0.1170358	total: 683ms	remaining: 105ms
260:	learn: 0.1170117	total: 686ms	remaining: 102ms
261:	learn: 0.1169642	total: 689ms	remaining: 99.9ms
262:	learn: 0.1169470	total: 691ms	remaining: 97.3ms
263:	learn: 0.1169097	total: 694ms	remaining: 94.6ms
264:	learn: 0.1168903	total: 697ms	remaining: 92.1ms
265:	learn: 0.1168398	total: 700ms	remaining: 89.5ms
266:	learn: 0.1168243	total: 703ms	remaining: 86.9ms
267:	learn: 0.1167921	total: 706ms	remaining: 84.3ms
268:	learn: 0.1167785	total: 709ms	remaining: 81.7ms
269:	learn: 0.1167549	total: 711ms	remaining: 79ms
270:	learn: 0.1167279	total: 714ms	remaining: 76.4ms
271:	learn: 0.1167134	total: 717ms	remaining: 73.8ms
272:	learn: 0.1167028	total: 720ms	remaining: 71.2ms
273:	learn: 0.1166811	total: 723ms	remaining: 68.6ms
274:	learn: 0.1166361	total: 725ms	remaining: 65.9ms
275:	learn: 0.1166049	total: 728ms	remaining: 63.3ms
276:	learn: 0.1165355	total: 731ms	remaining: 60.7ms
277:	learn: 0.1165220	total: 733ms	remaining: 58ms
278:	learn: 0.1164871	total: 736ms	remaining: 55.4ms
279:	learn: 0.1164469	total: 739ms	remaining: 52.8ms
280:	learn: 0.1164270	total: 742ms	remaining: 50.1ms
281:	learn: 0.1163889	total: 744ms	remaining: 47.5ms
282:	learn: 0.1163723	total: 746ms	remaining: 44.8ms
283:	learn: 0.1163515	total: 749ms	remaining: 42.2ms
284:	learn: 0.1163326	total: 751ms	remaining: 39.5ms
285:	learn: 0.1163199	total: 754ms	remaining: 36.9ms
286:	learn: 0.1162883	total: 757ms	remaining: 34.3ms
287:	learn: 0.1162730	total: 759ms	remaining: 31.6ms
288:	learn: 0.1162608	total: 762ms	remaining: 29ms
289:	learn: 0.1162500	total: 764ms	remaining: 26.3ms
290:	learn: 0.1162258	total: 767ms	remaining: 23.7ms
291:	learn: 0.1161925	total: 769ms	remaining: 21.1ms
292:	learn: 0.1161670	total: 772ms	remaining: 18.4ms
293:	learn: 0.1161381	total: 774ms	remaining: 15.8ms
294:	learn: 0.1161163	total: 777ms	remaining: 13.2ms
295:	learn: 0.1160956	total: 779ms	remaining: 10.5ms
296:	learn: 0.1160783	total: 782ms	remaining: 7.9ms
297:	learn: 0.1160643	total: 785ms	remaining: 5.26ms
298:	learn: 0.1160428	total: 787ms	remaining: 2.63ms
299:	learn: 0.1160224	total: 790ms	remaining: 0us

VotingClassifier(estimators=[('xgb',
                              Pipeline(steps=[('preprocessor',
                                               ColumnTransformer(remainder='passthrough',
                                                                 transformers=[('num',
                                                                                Pipeline(steps=[('imputer',
                                                                                                 SimpleImputer())]),
                                                                                Index(['Time_spent_Alone', 'Social_event_attendance', 'Going_outside',
       'Friends_circle_size', 'Post_frequency', 'match_p_is_null'],
      dtype='object')),
                                                                               ('cat',
                                                                                Pipeline(steps=[('encod...
                                                                                                 OrdinalEncoder(handle_unknown='use_encoded_value',
                                                                                                                unknown_value=-1))]),
                                                                                Index(['Stage_fear', 'Drained_after_socializing', 'match_p'], dtype='object'))])),
                                              ('classifier',
                                               <catboost.core.CatBoostClassifier object at 0x1450bbbf0>)]))],
                 n_jobs=-1, voting='soft',
                 weights=[np.float64(0.9702549091619229),
                          np.float64(0.9699849890551265),
                          np.float64(0.9703628568014153)])

In [33]:
predictions = ensemble.predict(X_test)
reverse_mapping = {1: 'Extrovert', 0: 'Introvert'}
final_predictions_text = pd.Series(predictions).map(reverse_mapping)

submission_df = pd.DataFrame({'id': test_df['id'], 'Personality': final_predictions_text})
submission_df.to_csv('submission.csv', index=False)

print("\nSubmission file 'submission.csv' created successfully.")
print("Submission file head:")
print(submission_df.head())

Submission file 'submission.csv' created successfully.
Submission file head:
      id Personality
0  18524   Extrovert
1  18525   Introvert
2  18526   Extrovert
3  18527   Extrovert
4  18528   Introvert

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

In [47]:
stacking = StackingClassifier(
    estimators=[
        ('xgb', best_xgb),
        ('lgbm', best_lgbm),
        ('cat', best_catboost)
    ],
    final_estimator=LogisticRegression(),
    cv=cv,
    n_jobs=-1,
    passthrough=False  # True = ajoute les features originales à l’input du méta-modèle
)

stacking.fit(X, y)
preds_stack = stacking.predict(X_test)

/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:44:25] WARNING: /Users/runner/work/xgboost/xgboost/src/context.cc:203: XGBoost is not compiled with CUDA support.
  bst.update(dtrain, iteration=i, fobj=obj)
/opt/miniconda3/lib/python3.13/site-packages/xgboost/training.py:183: UserWarning: [19:44:25] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[LightGBM] [Info] Number of positive: 13699, number of negative: 4825
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000740 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 18524, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739527 -> initscore=1.043512
[LightGBM] [Info] Start training from score 1.043512
0:	learn: 0.6129472	total: 59ms	remaining: 17.6s
1:	learn: 0.5456588	total: 61.4ms	remaining: 9.15s
2:	learn: 0.4866700	total: 64.2ms	remaining: 6.35s
3:	learn: 0.4376015	total: 66.5ms	remaining: 4.92s
4:	learn: 0.3952016	total: 69.3ms	remaining: 4.09s
5:	learn: 0.3603733	total: 72.1ms	remaining: 3.53s
6:	learn: 0.3295251	total: 74.2ms	remaining: 3.11s
7:	learn: 0.3023780	total: 76.7ms	remaining: 2.8s
8:	learn: 0.2792319	total: 79.3ms	remaining: 2.56s
9:	learn: 0.2593210	total: 81.7ms	remaining: 2.37s
10:	learn: 0.2425994	total: 84.6ms	remaining: 2.22s
11:	learn: 0.2278393	total: 87.8ms	remaining: 2.11s
12:	learn: 0.2157283	total: 90.3ms	remaining: 1.99s
13:	learn: 0.2047842	total: 93.4ms	remaining: 1.91s
14:	learn: 0.1957355	total: 96.2ms	remaining: 1.83s
15:	learn: 0.1875274	total: 99ms	remaining: 1.76s
16:	learn: 0.1804807	total: 102ms	remaining: 1.69s
17:	learn: 0.1745573	total: 105ms	remaining: 1.64s
18:	learn: 0.1690005	total: 107ms	remaining: 1.57s
19:	learn: 0.1642765	total: 109ms	remaining: 1.52s
20:	learn: 0.1603960	total: 111ms	remaining: 1.48s
21:	learn: 0.1566327	total: 114ms	remaining: 1.44s
22:	learn: 0.1535230	total: 116ms	remaining: 1.4s
23:	learn: 0.1506689	total: 119ms	remaining: 1.37s
24:	learn: 0.1479759	total: 121ms	remaining: 1.33s
25:	learn: 0.1457988	total: 123ms	remaining: 1.3s
26:	learn: 0.1438354	total: 126ms	remaining: 1.27s
27:	learn: 0.1419939	total: 128ms	remaining: 1.24s
28:	learn: 0.1403578	total: 130ms	remaining: 1.22s
29:	learn: 0.1388461	total: 133ms	remaining: 1.2s
30:	learn: 0.1375668	total: 136ms	remaining: 1.18s
31:	learn: 0.1364247	total: 138ms	remaining: 1.16s
32:	learn: 0.1353447	total: 140ms	remaining: 1.14s
33:	learn: 0.1343182	total: 143ms	remaining: 1.12s
34:	learn: 0.1333612	total: 146ms	remaining: 1.1s
35:	learn: 0.1325396	total: 149ms	remaining: 1.09s
36:	learn: 0.1318813	total: 152ms	remaining: 1.08s
37:	learn: 0.1311955	total: 154ms	remaining: 1.06s
38:	learn: 0.1306532	total: 156ms	remaining: 1.04s
39:	learn: 0.1300934	total: 159ms	remaining: 1.03s
40:	learn: 0.1296092	total: 162ms	remaining: 1.02s
41:	learn: 0.1291060	total: 165ms	remaining: 1.01s
42:	learn: 0.1287363	total: 167ms	remaining: 1000ms
43:	learn: 0.1283366	total: 170ms	remaining: 988ms
44:	learn: 0.1279593	total: 172ms	remaining: 976ms
45:	learn: 0.1276546	total: 174ms	remaining: 962ms
46:	learn: 0.1273858	total: 177ms	remaining: 953ms
47:	learn: 0.1271681	total: 180ms	remaining: 943ms
48:	learn: 0.1269419	total: 182ms	remaining: 931ms
49:	learn: 0.1267283	total: 184ms	remaining: 919ms
50:	learn: 0.1265428	total: 186ms	remaining: 908ms
51:	learn: 0.1263684	total: 188ms	remaining: 898ms
52:	learn: 0.1261922	total: 191ms	remaining: 888ms
53:	learn: 0.1259974	total: 193ms	remaining: 880ms
54:	learn: 0.1258232	total: 196ms	remaining: 872ms
55:	learn: 0.1256453	total: 198ms	remaining: 863ms
56:	learn: 0.1255118	total: 200ms	remaining: 854ms
57:	learn: 0.1254011	total: 203ms	remaining: 846ms
58:	learn: 0.1252967	total: 205ms	remaining: 838ms
59:	learn: 0.1251566	total: 208ms	remaining: 830ms
60:	learn: 0.1250407	total: 211ms	remaining: 825ms
61:	learn: 0.1248832	total: 213ms	remaining: 819ms
62:	learn: 0.1247249	total: 215ms	remaining: 810ms
63:	learn: 0.1246255	total: 217ms	remaining: 802ms
64:	learn: 0.1245315	total: 220ms	remaining: 795ms
65:	learn: 0.1244648	total: 222ms	remaining: 788ms
66:	learn: 0.1243995	total: 225ms	remaining: 781ms
67:	learn: 0.1243444	total: 227ms	remaining: 775ms
68:	learn: 0.1242370	total: 229ms	remaining: 768ms
69:	learn: 0.1241477	total: 232ms	remaining: 762ms
70:	learn: 0.1240751	total: 234ms	remaining: 756ms
71:	learn: 0.1239889	total: 237ms	remaining: 750ms
72:	learn: 0.1238908	total: 239ms	remaining: 744ms
73:	learn: 0.1237767	total: 242ms	remaining: 738ms
74:	learn: 0.1237103	total: 244ms	remaining: 732ms
75:	learn: 0.1235964	total: 246ms	remaining: 725ms
76:	learn: 0.1235337	total: 249ms	remaining: 721ms
77:	learn: 0.1234508	total: 252ms	remaining: 716ms
78:	learn: 0.1233840	total: 254ms	remaining: 711ms
79:	learn: 0.1232964	total: 257ms	remaining: 706ms
80:	learn: 0.1232363	total: 261ms	remaining: 704ms
81:	learn: 0.1231752	total: 263ms	remaining: 700ms
82:	learn: 0.1231077	total: 266ms	remaining: 694ms
83:	learn: 0.1230447	total: 268ms	remaining: 689ms
84:	learn: 0.1230042	total: 270ms	remaining: 683ms
85:	learn: 0.1229493	total: 272ms	remaining: 678ms
86:	learn: 0.1228864	total: 275ms	remaining: 674ms
87:	learn: 0.1228109	total: 278ms	remaining: 671ms
88:	learn: 0.1227694	total: 281ms	remaining: 666ms
89:	learn: 0.1226805	total: 283ms	remaining: 661ms
90:	learn: 0.1226109	total: 286ms	remaining: 657ms
91:	learn: 0.1225432	total: 289ms	remaining: 652ms
92:	learn: 0.1225080	total: 291ms	remaining: 648ms
93:	learn: 0.1224630	total: 294ms	remaining: 644ms
94:	learn: 0.1224142	total: 296ms	remaining: 639ms
95:	learn: 0.1223718	total: 299ms	remaining: 635ms
96:	learn: 0.1223405	total: 301ms	remaining: 630ms
97:	learn: 0.1222762	total: 303ms	remaining: 625ms
98:	learn: 0.1222201	total: 306ms	remaining: 621ms
99:	learn: 0.1221493	total: 308ms	remaining: 617ms
100:	learn: 0.1221099	total: 311ms	remaining: 612ms
101:	learn: 0.1220647	total: 313ms	remaining: 608ms
102:	learn: 0.1220141	total: 315ms	remaining: 603ms
103:	learn: 0.1219795	total: 318ms	remaining: 599ms
104:	learn: 0.1219407	total: 320ms	remaining: 595ms
105:	learn: 0.1218964	total: 323ms	remaining: 590ms
106:	learn: 0.1218616	total: 325ms	remaining: 586ms
107:	learn: 0.1218258	total: 327ms	remaining: 582ms
108:	learn: 0.1217804	total: 330ms	remaining: 578ms
109:	learn: 0.1217417	total: 332ms	remaining: 574ms
110:	learn: 0.1216640	total: 334ms	remaining: 569ms
111:	learn: 0.1216177	total: 337ms	remaining: 565ms
112:	learn: 0.1215750	total: 339ms	remaining: 561ms
113:	learn: 0.1215351	total: 342ms	remaining: 558ms
114:	learn: 0.1214729	total: 344ms	remaining: 554ms
115:	learn: 0.1214334	total: 346ms	remaining: 550ms
116:	learn: 0.1213966	total: 348ms	remaining: 545ms
117:	learn: 0.1213657	total: 351ms	remaining: 541ms
118:	learn: 0.1213393	total: 353ms	remaining: 537ms
119:	learn: 0.1213144	total: 355ms	remaining: 532ms
120:	learn: 0.1212772	total: 357ms	remaining: 528ms
121:	learn: 0.1212343	total: 359ms	remaining: 524ms
122:	learn: 0.1212080	total: 362ms	remaining: 520ms
123:	learn: 0.1211772	total: 364ms	remaining: 516ms
124:	learn: 0.1211490	total: 366ms	remaining: 512ms
125:	learn: 0.1211074	total: 368ms	remaining: 509ms
126:	learn: 0.1210772	total: 371ms	remaining: 505ms
127:	learn: 0.1210496	total: 374ms	remaining: 502ms
128:	learn: 0.1210041	total: 376ms	remaining: 499ms
129:	learn: 0.1209772	total: 379ms	remaining: 495ms
130:	learn: 0.1209514	total: 381ms	remaining: 491ms
131:	learn: 0.1209200	total: 383ms	remaining: 488ms
132:	learn: 0.1208837	total: 386ms	remaining: 484ms
133:	learn: 0.1208390	total: 388ms	remaining: 481ms
134:	learn: 0.1207931	total: 391ms	remaining: 478ms
135:	learn: 0.1207654	total: 393ms	remaining: 474ms
136:	learn: 0.1207203	total: 395ms	remaining: 471ms
137:	learn: 0.1207071	total: 398ms	remaining: 467ms
138:	learn: 0.1206463	total: 400ms	remaining: 464ms
139:	learn: 0.1206225	total: 403ms	remaining: 460ms
140:	learn: 0.1206003	total: 405ms	remaining: 456ms
141:	learn: 0.1205624	total: 407ms	remaining: 453ms
142:	learn: 0.1205475	total: 409ms	remaining: 449ms
143:	learn: 0.1205039	total: 412ms	remaining: 446ms
144:	learn: 0.1204722	total: 415ms	remaining: 443ms
145:	learn: 0.1204344	total: 417ms	remaining: 440ms
146:	learn: 0.1203770	total: 420ms	remaining: 437ms
147:	learn: 0.1203439	total: 422ms	remaining: 434ms
148:	learn: 0.1203095	total: 424ms	remaining: 430ms
149:	learn: 0.1202973	total: 427ms	remaining: 427ms
150:	learn: 0.1202577	total: 429ms	remaining: 423ms
151:	learn: 0.1202314	total: 431ms	remaining: 420ms
152:	learn: 0.1202057	total: 434ms	remaining: 417ms
153:	learn: 0.1201588	total: 436ms	remaining: 414ms
154:	learn: 0.1201404	total: 439ms	remaining: 410ms
155:	learn: 0.1201092	total: 441ms	remaining: 407ms
156:	learn: 0.1200601	total: 444ms	remaining: 404ms
157:	learn: 0.1200256	total: 446ms	remaining: 401ms
158:	learn: 0.1199264	total: 449ms	remaining: 398ms
159:	learn: 0.1198920	total: 451ms	remaining: 395ms
160:	learn: 0.1198678	total: 453ms	remaining: 391ms
161:	learn: 0.1198313	total: 456ms	remaining: 388ms
162:	learn: 0.1197992	total: 458ms	remaining: 385ms
163:	learn: 0.1197633	total: 461ms	remaining: 382ms
164:	learn: 0.1196901	total: 463ms	remaining: 379ms
165:	learn: 0.1196533	total: 466ms	remaining: 376ms
166:	learn: 0.1196148	total: 468ms	remaining: 373ms
167:	learn: 0.1195673	total: 470ms	remaining: 370ms
168:	learn: 0.1195462	total: 473ms	remaining: 367ms
169:	learn: 0.1195160	total: 475ms	remaining: 364ms
170:	learn: 0.1194755	total: 478ms	remaining: 360ms
171:	learn: 0.1194511	total: 480ms	remaining: 357ms
172:	learn: 0.1194278	total: 482ms	remaining: 354ms
173:	learn: 0.1193773	total: 485ms	remaining: 351ms
174:	learn: 0.1193339	total: 487ms	remaining: 348ms
175:	learn: 0.1193104	total: 489ms	remaining: 345ms
176:	learn: 0.1192632	total: 491ms	remaining: 341ms
177:	learn: 0.1192242	total: 494ms	remaining: 338ms
178:	learn: 0.1192089	total: 496ms	remaining: 335ms
179:	learn: 0.1191814	total: 498ms	remaining: 332ms
180:	learn: 0.1191559	total: 501ms	remaining: 329ms
181:	learn: 0.1191206	total: 504ms	remaining: 326ms
182:	learn: 0.1190997	total: 506ms	remaining: 323ms
183:	learn: 0.1190608	total: 508ms	remaining: 320ms
184:	learn: 0.1190257	total: 510ms	remaining: 317ms
185:	learn: 0.1189858	total: 513ms	remaining: 314ms
186:	learn: 0.1189472	total: 515ms	remaining: 311ms
187:	learn: 0.1189150	total: 517ms	remaining: 308ms
188:	learn: 0.1188785	total: 520ms	remaining: 305ms
189:	learn: 0.1188431	total: 522ms	remaining: 302ms
190:	learn: 0.1188187	total: 525ms	remaining: 299ms
191:	learn: 0.1187886	total: 527ms	remaining: 296ms
192:	learn: 0.1187640	total: 529ms	remaining: 293ms
193:	learn: 0.1187431	total: 531ms	remaining: 290ms
194:	learn: 0.1187107	total: 533ms	remaining: 287ms
195:	learn: 0.1186883	total: 536ms	remaining: 284ms
196:	learn: 0.1186530	total: 538ms	remaining: 281ms
197:	learn: 0.1186242	total: 540ms	remaining: 278ms
198:	learn: 0.1185983	total: 543ms	remaining: 275ms
199:	learn: 0.1185675	total: 545ms	remaining: 272ms
200:	learn: 0.1185471	total: 547ms	remaining: 269ms
201:	learn: 0.1185236	total: 549ms	remaining: 266ms
202:	learn: 0.1184927	total: 552ms	remaining: 264ms
203:	learn: 0.1184708	total: 554ms	remaining: 261ms
204:	learn: 0.1184443	total: 556ms	remaining: 258ms
205:	learn: 0.1184189	total: 559ms	remaining: 255ms
206:	learn: 0.1183936	total: 561ms	remaining: 252ms
207:	learn: 0.1183495	total: 563ms	remaining: 249ms
208:	learn: 0.1183295	total: 566ms	remaining: 246ms
209:	learn: 0.1182951	total: 568ms	remaining: 243ms
210:	learn: 0.1182722	total: 571ms	remaining: 241ms
211:	learn: 0.1182389	total: 573ms	remaining: 238ms
212:	learn: 0.1182052	total: 575ms	remaining: 235ms
213:	learn: 0.1181494	total: 578ms	remaining: 232ms
214:	learn: 0.1181217	total: 580ms	remaining: 229ms
215:	learn: 0.1181020	total: 583ms	remaining: 227ms
216:	learn: 0.1180661	total: 586ms	remaining: 224ms
217:	learn: 0.1180476	total: 588ms	remaining: 221ms
218:	learn: 0.1180237	total: 591ms	remaining: 219ms
219:	learn: 0.1180085	total: 593ms	remaining: 216ms
220:	learn: 0.1179920	total: 595ms	remaining: 213ms
221:	learn: 0.1179647	total: 598ms	remaining: 210ms
222:	learn: 0.1179458	total: 600ms	remaining: 207ms
223:	learn: 0.1179168	total: 603ms	remaining: 205ms
224:	learn: 0.1178891	total: 605ms	remaining: 202ms
225:	learn: 0.1178628	total: 607ms	remaining: 199ms
226:	learn: 0.1178381	total: 610ms	remaining: 196ms
227:	learn: 0.1178157	total: 612ms	remaining: 193ms
228:	learn: 0.1177838	total: 614ms	remaining: 191ms
229:	learn: 0.1177616	total: 617ms	remaining: 188ms
230:	learn: 0.1177451	total: 619ms	remaining: 185ms
231:	learn: 0.1177204	total: 621ms	remaining: 182ms
232:	learn: 0.1177048	total: 624ms	remaining: 179ms
233:	learn: 0.1176782	total: 626ms	remaining: 177ms
234:	learn: 0.1176483	total: 628ms	remaining: 174ms
235:	learn: 0.1176359	total: 631ms	remaining: 171ms
236:	learn: 0.1176103	total: 633ms	remaining: 168ms
237:	learn: 0.1175802	total: 636ms	remaining: 166ms
238:	learn: 0.1175595	total: 638ms	remaining: 163ms
239:	learn: 0.1175438	total: 640ms	remaining: 160ms
240:	learn: 0.1175167	total: 643ms	remaining: 157ms
241:	learn: 0.1174766	total: 645ms	remaining: 155ms
242:	learn: 0.1174634	total: 648ms	remaining: 152ms
243:	learn: 0.1174491	total: 650ms	remaining: 149ms
244:	learn: 0.1174314	total: 652ms	remaining: 146ms
245:	learn: 0.1174130	total: 655ms	remaining: 144ms
246:	learn: 0.1173952	total: 657ms	remaining: 141ms
247:	learn: 0.1173550	total: 660ms	remaining: 138ms
248:	learn: 0.1173321	total: 663ms	remaining: 136ms
249:	learn: 0.1172951	total: 665ms	remaining: 133ms
250:	learn: 0.1172781	total: 668ms	remaining: 130ms
251:	learn: 0.1172494	total: 670ms	remaining: 128ms
252:	learn: 0.1172377	total: 673ms	remaining: 125ms
253:	learn: 0.1172033	total: 675ms	remaining: 122ms
254:	learn: 0.1171804	total: 677ms	remaining: 119ms
255:	learn: 0.1171545	total: 679ms	remaining: 117ms
256:	learn: 0.1171330	total: 682ms	remaining: 114ms
257:	learn: 0.1170922	total: 684ms	remaining: 111ms
258:	learn: 0.1170625	total: 686ms	remaining: 109ms
259:	learn: 0.1170358	total: 688ms	remaining: 106ms
260:	learn: 0.1170117	total: 691ms	remaining: 103ms
261:	learn: 0.1169642	total: 693ms	remaining: 101ms
262:	learn: 0.1169470	total: 696ms	remaining: 97.9ms
263:	learn: 0.1169097	total: 698ms	remaining: 95.2ms
264:	learn: 0.1168903	total: 700ms	remaining: 92.5ms
265:	learn: 0.1168398	total: 703ms	remaining: 89.8ms
266:	learn: 0.1168243	total: 705ms	remaining: 87.1ms
267:	learn: 0.1167921	total: 707ms	remaining: 84.5ms
268:	learn: 0.1167785	total: 709ms	remaining: 81.8ms
269:	learn: 0.1167549	total: 711ms	remaining: 79ms
270:	learn: 0.1167279	total: 713ms	remaining: 76.3ms
271:	learn: 0.1167134	total: 716ms	remaining: 73.7ms
272:	learn: 0.1167028	total: 718ms	remaining: 71ms
273:	learn: 0.1166811	total: 720ms	remaining: 68.3ms
274:	learn: 0.1166361	total: 722ms	remaining: 65.7ms
275:	learn: 0.1166049	total: 724ms	remaining: 63ms
276:	learn: 0.1165355	total: 727ms	remaining: 60.3ms
277:	learn: 0.1165220	total: 729ms	remaining: 57.7ms
278:	learn: 0.1164871	total: 731ms	remaining: 55ms
279:	learn: 0.1164469	total: 734ms	remaining: 52.4ms
280:	learn: 0.1164270	total: 736ms	remaining: 49.7ms
281:	learn: 0.1163889	total: 738ms	remaining: 47.1ms
282:	learn: 0.1163723	total: 740ms	remaining: 44.5ms
283:	learn: 0.1163515	total: 742ms	remaining: 41.8ms
284:	learn: 0.1163326	total: 744ms	remaining: 39.2ms
285:	learn: 0.1163199	total: 747ms	remaining: 36.6ms
286:	learn: 0.1162883	total: 750ms	remaining: 33.9ms
287:	learn: 0.1162730	total: 752ms	remaining: 31.3ms
288:	learn: 0.1162608	total: 754ms	remaining: 28.7ms
289:	learn: 0.1162500	total: 756ms	remaining: 26.1ms
290:	learn: 0.1162258	total: 758ms	remaining: 23.5ms
291:	learn: 0.1161925	total: 761ms	remaining: 20.8ms
292:	learn: 0.1161670	total: 763ms	remaining: 18.2ms
293:	learn: 0.1161381	total: 765ms	remaining: 15.6ms
294:	learn: 0.1161163	total: 768ms	remaining: 13ms
295:	learn: 0.1160956	total: 771ms	remaining: 10.4ms
296:	learn: 0.1160783	total: 773ms	remaining: 7.8ms
297:	learn: 0.1160643	total: 775ms	remaining: 5.2ms
298:	learn: 0.1160428	total: 777ms	remaining: 2.6ms
299:	learn: 0.1160224	total: 779ms	remaining: 0us

[19:44:27] WARNING: /Users/runner/work/xgboost/xgboost/src/context.cc:203: XGBoost is not compiled with CUDA support.
[19:44:27] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

[19:44:27] WARNING: /Users/runner/work/xgboost/xgboost/src/context.cc:203: XGBoost is not compiled with CUDA support.
[19:44:27] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

[19:44:27] WARNING: /Users/runner/work/xgboost/xgboost/src/context.cc:203: XGBoost is not compiled with CUDA support.
[19:44:27] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

[19:44:27] WARNING: /Users/runner/work/xgboost/xgboost/src/context.cc:203: XGBoost is not compiled with CUDA support.
[19:44:27] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

[19:44:27] WARNING: /Users/runner/work/xgboost/xgboost/src/context.cc:203: XGBoost is not compiled with CUDA support.
[19:44:27] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Number of positive: 10959, number of negative: 3860
[LightGBM] [Info] Number of positive: 10960, number of negative: 3860
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004318 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004565 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004730 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004732 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.007057 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 74
[LightGBM] [Info] Number of data points in the train set: 14819, number of used features: 9
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Number of data points in the train set: 14820, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739524 -> initscore=1.043494
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.739541 -> initscore=1.043585
[LightGBM] [Info] Start training from score 1.043494
[LightGBM] [Info] Start training from score 1.043585
0:	learn: 0.6146117	total: 141ms	remaining: 42.2s
0:	learn: 0.6139477	total: 253ms	remaining: 1m 15s
0:	learn: 0.6140430	total: 134ms	remaining: 40.2s
1:	learn: 0.5458120	total: 256ms	remaining: 38.2s
1:	learn: 0.5457391	total: 147ms	remaining: 21.9s
1:	learn: 0.5455918	total: 139ms	remaining: 20.7s
2:	learn: 0.4885992	total: 261ms	remaining: 25.8s
0:	learn: 0.6122698	total: 209ms	remaining: 1m 2s
2:	learn: 0.4853126	total: 143ms	remaining: 14.1s
2:	learn: 0.4852233	total: 152ms	remaining: 15.1s
3:	learn: 0.4399626	total: 265ms	remaining: 19.6s
1:	learn: 0.5443252	total: 213ms	remaining: 31.7s
3:	learn: 0.4357437	total: 146ms	remaining: 10.8s
3:	learn: 0.4354816	total: 157ms	remaining: 11.6s
4:	learn: 0.3979565	total: 270ms	remaining: 15.9s
2:	learn: 0.4861429	total: 218ms	remaining: 21.5s
5:	learn: 0.3631436	total: 273ms	remaining: 13.4s
4:	learn: 0.3933478	total: 164ms	remaining: 9.67s
3:	learn: 0.4365895	total: 222ms	remaining: 16.4s
6:	learn: 0.3322074	total: 276ms	remaining: 11.6s
7:	learn: 0.3057827	total: 281ms	remaining: 10.3s
4:	learn: 0.3936546	total: 230ms	remaining: 13.6s
5:	learn: 0.3589398	total: 173ms	remaining: 8.47s
5:	learn: 0.3585143	total: 234ms	remaining: 11.5s
6:	learn: 0.3279806	total: 179ms	remaining: 7.51s
6:	learn: 0.3272303	total: 238ms	remaining: 9.98s
4:	learn: 0.3935144	total: 181ms	remaining: 10.7s
8:	learn: 0.2829500	total: 301ms	remaining: 9.74s
7:	learn: 0.3004268	total: 251ms	remaining: 9.15s
5:	learn: 0.3569829	total: 194ms	remaining: 9.51s
8:	learn: 0.2776794	total: 276ms	remaining: 8.94s
7:	learn: 0.3017079	total: 228ms	remaining: 8.3s
9:	learn: 0.2576101	total: 281ms	remaining: 8.16s
9:	learn: 0.2633710	total: 341ms	remaining: 9.89s
0:	learn: 0.6124611	total: 49.1ms	remaining: 14.7s
6:	learn: 0.3257621	total: 225ms	remaining: 9.43s
8:	learn: 0.2794224	total: 235ms	remaining: 7.6s
10:	learn: 0.2461647	total: 344ms	remaining: 9.04s
10:	learn: 0.2409793	total: 286ms	remaining: 7.52s
9:	learn: 0.2612751	total: 239ms	remaining: 6.93s
1:	learn: 0.5435416	total: 55.8ms	remaining: 8.31s
11:	learn: 0.2259232	total: 290ms	remaining: 6.96s
11:	learn: 0.2312752	total: 359ms	remaining: 8.62s
7:	learn: 0.3001098	total: 241ms	remaining: 8.8s
10:	learn: 0.2435316	total: 256ms	remaining: 6.72s
12:	learn: 0.2131489	total: 306ms	remaining: 6.75s
2:	learn: 0.4849874	total: 72.2ms	remaining: 7.15s
12:	learn: 0.2187251	total: 366ms	remaining: 8.09s
8:	learn: 0.2778669	total: 250ms	remaining: 8.08s
11:	learn: 0.2286360	total: 261ms	remaining: 6.26s
13:	learn: 0.2026968	total: 311ms	remaining: 6.35s
13:	learn: 0.2077152	total: 372ms	remaining: 7.6s
3:	learn: 0.4342327	total: 80.6ms	remaining: 5.96s
9:	learn: 0.2586257	total: 256ms	remaining: 7.43s
14:	learn: 0.1932248	total: 317ms	remaining: 6.02s
4:	learn: 0.3921013	total: 83.9ms	remaining: 4.95s
12:	learn: 0.2165319	total: 269ms	remaining: 5.93s
14:	learn: 0.1981458	total: 379ms	remaining: 7.21s
10:	learn: 0.2424358	total: 262ms	remaining: 6.89s
5:	learn: 0.3556647	total: 90.1ms	remaining: 4.41s
15:	learn: 0.1850377	total: 324ms	remaining: 5.75s
15:	learn: 0.1900412	total: 386ms	remaining: 6.84s
11:	learn: 0.2283644	total: 268ms	remaining: 6.43s
13:	learn: 0.2060948	total: 278ms	remaining: 5.67s
6:	learn: 0.3250960	total: 97.3ms	remaining: 4.07s
12:	learn: 0.2164295	total: 273ms	remaining: 6.02s
16:	learn: 0.1780944	total: 332ms	remaining: 5.52s
16:	learn: 0.1828202	total: 394ms	remaining: 6.56s
14:	learn: 0.1968697	total: 285ms	remaining: 5.42s
7:	learn: 0.2985695	total: 104ms	remaining: 3.8s
13:	learn: 0.2057179	total: 280ms	remaining: 5.72s
17:	learn: 0.1718681	total: 340ms	remaining: 5.33s
17:	learn: 0.1768857	total: 401ms	remaining: 6.28s
15:	learn: 0.1885267	total: 295ms	remaining: 5.23s
14:	learn: 0.1959212	total: 287ms	remaining: 5.45s
8:	learn: 0.2757035	total: 113ms	remaining: 3.65s
18:	learn: 0.1666795	total: 348ms	remaining: 5.14s
16:	learn: 0.1813582	total: 301ms	remaining: 5.01s
17:	learn: 0.1751439	total: 308ms	remaining: 4.83s
18:	learn: 0.1696942	total: 317ms	remaining: 4.69s
15:	learn: 0.1878908	total: 311ms	remaining: 5.53s
18:	learn: 0.1712106	total: 444ms	remaining: 6.56s
9:	learn: 0.2562302	total: 151ms	remaining: 4.38s
19:	learn: 0.1620929	total: 385ms	remaining: 5.39s
10:	learn: 0.2392293	total: 164ms	remaining: 4.31s
20:	learn: 0.1578877	total: 409ms	remaining: 5.44s
19:	learn: 0.1663133	total: 470ms	remaining: 6.59s
21:	learn: 0.1544757	total: 417ms	remaining: 5.27s
20:	learn: 0.1622120	total: 482ms	remaining: 6.4s
16:	learn: 0.1811088	total: 367ms	remaining: 6.1s
11:	learn: 0.2250007	total: 192ms	remaining: 4.6s
12:	learn: 0.2130489	total: 200ms	remaining: 4.41s
19:	learn: 0.1651182	total: 387ms	remaining: 5.42s
17:	learn: 0.1751553	total: 379ms	remaining: 5.94s
20:	learn: 0.1608591	total: 399ms	remaining: 5.3s
21:	learn: 0.1584999	total: 512ms	remaining: 6.47s
13:	learn: 0.2024308	total: 224ms	remaining: 4.58s
18:	learn: 0.1697158	total: 409ms	remaining: 6.05s
22:	learn: 0.1512039	total: 475ms	remaining: 5.72s
21:	learn: 0.1573162	total: 436ms	remaining: 5.51s
14:	learn: 0.1932085	total: 252ms	remaining: 4.79s
23:	learn: 0.1483725	total: 485ms	remaining: 5.58s
22:	learn: 0.1552820	total: 553ms	remaining: 6.66s
22:	learn: 0.1541334	total: 452ms	remaining: 5.45s
24:	learn: 0.1457490	total: 494ms	remaining: 5.44s
23:	learn: 0.1513006	total: 466ms	remaining: 5.36s
25:	learn: 0.1434987	total: 509ms	remaining: 5.36s
23:	learn: 0.1523430	total: 578ms	remaining: 6.65s
26:	learn: 0.1415308	total: 515ms	remaining: 5.21s
24:	learn: 0.1490458	total: 477ms	remaining: 5.25s
19:	learn: 0.1649931	total: 469ms	remaining: 6.56s
15:	learn: 0.1853166	total: 296ms	remaining: 5.25s
20:	learn: 0.1605915	total: 474ms	remaining: 6.3s
16:	learn: 0.1786508	total: 299ms	remaining: 4.99s
24:	learn: 0.1499307	total: 593ms	remaining: 6.53s
21:	learn: 0.1569660	total: 479ms	remaining: 6.06s
22:	learn: 0.1535606	total: 486ms	remaining: 5.86s
27:	learn: 0.1396922	total: 540ms	remaining: 5.25s
25:	learn: 0.1467798	total: 502ms	remaining: 5.29s
17:	learn: 0.1729430	total: 318ms	remaining: 4.98s
28:	learn: 0.1381201	total: 546ms	remaining: 5.1s
18:	learn: 0.1677348	total: 326ms	remaining: 4.82s
25:	learn: 0.1476251	total: 620ms	remaining: 6.54s
19:	learn: 0.1633079	total: 331ms	remaining: 4.64s
26:	learn: 0.1455437	total: 628ms	remaining: 6.35s
23:	learn: 0.1505635	total: 511ms	remaining: 5.88s
26:	learn: 0.1446816	total: 526ms	remaining: 5.32s
20:	learn: 0.1590932	total: 344ms	remaining: 4.57s
27:	learn: 0.1430131	total: 534ms	remaining: 5.19s
24:	learn: 0.1481090	total: 526ms	remaining: 5.79s
27:	learn: 0.1436615	total: 648ms	remaining: 6.29s
29:	learn: 0.1366553	total: 580ms	remaining: 5.22s
25:	learn: 0.1457107	total: 537ms	remaining: 5.66s
30:	learn: 0.1354162	total: 587ms	remaining: 5.09s
31:	learn: 0.1342532	total: 591ms	remaining: 4.95s
28:	learn: 0.1419718	total: 660ms	remaining: 6.17s
28:	learn: 0.1412919	total: 558ms	remaining: 5.21s
21:	learn: 0.1555260	total: 375ms	remaining: 4.74s
29:	learn: 0.1404984	total: 674ms	remaining: 6.06s
29:	learn: 0.1397911	total: 563ms	remaining: 5.06s
22:	learn: 0.1522848	total: 386ms	remaining: 4.65s
30:	learn: 0.1391759	total: 680ms	remaining: 5.9s
26:	learn: 0.1436484	total: 567ms	remaining: 5.73s
32:	learn: 0.1330505	total: 616ms	remaining: 4.99s
23:	learn: 0.1494686	total: 394ms	remaining: 4.53s
27:	learn: 0.1419907	total: 577ms	remaining: 5.61s
33:	learn: 0.1321247	total: 627ms	remaining: 4.9s
30:	learn: 0.1385379	total: 586ms	remaining: 5.08s
28:	learn: 0.1402482	total: 584ms	remaining: 5.46s
31:	learn: 0.1372876	total: 594ms	remaining: 4.98s
31:	learn: 0.1379574	total: 707ms	remaining: 5.92s
29:	learn: 0.1387735	total: 589ms	remaining: 5.3s
32:	learn: 0.1369050	total: 715ms	remaining: 5.79s
24:	learn: 0.1469542	total: 422ms	remaining: 4.64s
34:	learn: 0.1312455	total: 649ms	remaining: 4.92s
25:	learn: 0.1448051	total: 428ms	remaining: 4.5s
35:	learn: 0.1304826	total: 656ms	remaining: 4.81s
33:	learn: 0.1358918	total: 729ms	remaining: 5.71s
32:	learn: 0.1364199	total: 622ms	remaining: 5.03s
36:	learn: 0.1298136	total: 667ms	remaining: 4.74s
33:	learn: 0.1354419	total: 628ms	remaining: 4.91s
26:	learn: 0.1428792	total: 450ms	remaining: 4.55s
30:	learn: 0.1374205	total: 629ms	remaining: 5.46s
34:	learn: 0.1350607	total: 749ms	remaining: 5.67s
27:	learn: 0.1410349	total: 459ms	remaining: 4.46s
31:	learn: 0.1361519	total: 637ms	remaining: 5.34s
34:	learn: 0.1346644	total: 646ms	remaining: 4.89s
37:	learn: 0.1290834	total: 675ms	remaining: 4.65s
35:	learn: 0.1342361	total: 765ms	remaining: 5.61s
35:	learn: 0.1338527	total: 657ms	remaining: 4.82s
36:	learn: 0.1334941	total: 771ms	remaining: 5.48s
32:	learn: 0.1350922	total: 650ms	remaining: 5.26s
38:	learn: 0.1285322	total: 693ms	remaining: 4.64s
36:	learn: 0.1331577	total: 667ms	remaining: 4.74s
28:	learn: 0.1395479	total: 487ms	remaining: 4.55s
33:	learn: 0.1341277	total: 659ms	remaining: 5.16s
39:	learn: 0.1279863	total: 702ms	remaining: 4.57s
37:	learn: 0.1329243	total: 792ms	remaining: 5.46s
37:	learn: 0.1325380	total: 686ms	remaining: 4.73s
34:	learn: 0.1332634	total: 678ms	remaining: 5.13s
38:	learn: 0.1319735	total: 694ms	remaining: 4.65s
29:	learn: 0.1381157	total: 514ms	remaining: 4.63s
38:	learn: 0.1323454	total: 811ms	remaining: 5.42s
40:	learn: 0.1275432	total: 725ms	remaining: 4.58s
30:	learn: 0.1368301	total: 520ms	remaining: 4.51s
39:	learn: 0.1317195	total: 818ms	remaining: 5.31s
35:	learn: 0.1324676	total: 701ms	remaining: 5.14s
40:	learn: 0.1312276	total: 824ms	remaining: 5.21s
41:	learn: 0.1270511	total: 740ms	remaining: 4.54s
39:	learn: 0.1314352	total: 717ms	remaining: 4.66s
31:	learn: 0.1356350	total: 541ms	remaining: 4.53s
42:	learn: 0.1266521	total: 752ms	remaining: 4.49s
36:	learn: 0.1318030	total: 717ms	remaining: 5.09s
40:	learn: 0.1310021	total: 727ms	remaining: 4.59s
32:	learn: 0.1345652	total: 547ms	remaining: 4.43s
43:	learn: 0.1262788	total: 755ms	remaining: 4.39s
37:	learn: 0.1311762	total: 720ms	remaining: 4.96s
41:	learn: 0.1308143	total: 843ms	remaining: 5.18s
41:	learn: 0.1305788	total: 733ms	remaining: 4.5s
38:	learn: 0.1306438	total: 724ms	remaining: 4.84s
42:	learn: 0.1304291	total: 847ms	remaining: 5.06s
33:	learn: 0.1335100	total: 554ms	remaining: 4.33s
34:	learn: 0.1327556	total: 557ms	remaining: 4.22s
39:	learn: 0.1301436	total: 728ms	remaining: 4.73s
42:	learn: 0.1301777	total: 739ms	remaining: 4.42s
44:	learn: 0.1259512	total: 765ms	remaining: 4.33s
43:	learn: 0.1300016	total: 853ms	remaining: 4.96s
40:	learn: 0.1296991	total: 734ms	remaining: 4.64s
45:	learn: 0.1256733	total: 770ms	remaining: 4.25s
43:	learn: 0.1298062	total: 746ms	remaining: 4.34s
44:	learn: 0.1296700	total: 859ms	remaining: 4.87s
46:	learn: 0.1253640	total: 777ms	remaining: 4.18s
44:	learn: 0.1294303	total: 752ms	remaining: 4.26s
41:	learn: 0.1292651	total: 742ms	remaining: 4.56s
45:	learn: 0.1292292	total: 866ms	remaining: 4.78s
35:	learn: 0.1319696	total: 573ms	remaining: 4.2s
36:	learn: 0.1311711	total: 576ms	remaining: 4.09s
46:	learn: 0.1289426	total: 871ms	remaining: 4.69s
42:	learn: 0.1288387	total: 750ms	remaining: 4.48s
37:	learn: 0.1304227	total: 580ms	remaining: 4s
45:	learn: 0.1290892	total: 764ms	remaining: 4.22s
43:	learn: 0.1284511	total: 755ms	remaining: 4.39s
38:	learn: 0.1297263	total: 589ms	remaining: 3.94s
46:	learn: 0.1287479	total: 771ms	remaining: 4.15s
44:	learn: 0.1280790	total: 762ms	remaining: 4.32s
47:	learn: 0.1284682	total: 776ms	remaining: 4.07s
47:	learn: 0.1286909	total: 889ms	remaining: 4.67s
39:	learn: 0.1291699	total: 596ms	remaining: 3.87s
48:	learn: 0.1281686	total: 783ms	remaining: 4.01s
45:	learn: 0.1277948	total: 779ms	remaining: 4.3s
47:	learn: 0.1250004	total: 815ms	remaining: 4.28s
40:	learn: 0.1285600	total: 618ms	remaining: 3.9s
48:	learn: 0.1247319	total: 831ms	remaining: 4.25s
48:	learn: 0.1284489	total: 925ms	remaining: 4.74s
41:	learn: 0.1281280	total: 638ms	remaining: 3.92s
46:	learn: 0.1275237	total: 810ms	remaining: 4.36s
49:	learn: 0.1282126	total: 935ms	remaining: 4.68s
42:	learn: 0.1276353	total: 654ms	remaining: 3.91s
47:	learn: 0.1272372	total: 828ms	remaining: 4.35s
49:	learn: 0.1244318	total: 865ms	remaining: 4.33s
49:	learn: 0.1279197	total: 840ms	remaining: 4.2s
50:	learn: 0.1242468	total: 873ms	remaining: 4.26s
50:	learn: 0.1277143	total: 852ms	remaining: 4.16s
50:	learn: 0.1279757	total: 977ms	remaining: 4.77s
48:	learn: 0.1269976	total: 855ms	remaining: 4.38s
43:	learn: 0.1271824	total: 686ms	remaining: 3.99s
51:	learn: 0.1240616	total: 897ms	remaining: 4.28s
51:	learn: 0.1274745	total: 885ms	remaining: 4.22s
51:	learn: 0.1278217	total: 998ms	remaining: 4.76s
52:	learn: 0.1276351	total: 1.01s	remaining: 4.71s
49:	learn: 0.1267740	total: 894ms	remaining: 4.47s
52:	learn: 0.1238863	total: 926ms	remaining: 4.32s
44:	learn: 0.1268222	total: 731ms	remaining: 4.14s
53:	learn: 0.1235969	total: 937ms	remaining: 4.27s
45:	learn: 0.1265059	total: 739ms	remaining: 4.08s
52:	learn: 0.1272560	total: 922ms	remaining: 4.3s
53:	learn: 0.1270787	total: 934ms	remaining: 4.25s
53:	learn: 0.1274237	total: 1.04s	remaining: 4.76s
54:	learn: 0.1271289	total: 1.05s	remaining: 4.7s
55:	learn: 0.1269580	total: 1.06s	remaining: 4.62s
54:	learn: 0.1233952	total: 976ms	remaining: 4.35s
50:	learn: 0.1265080	total: 939ms	remaining: 4.59s
46:	learn: 0.1262241	total: 782ms	remaining: 4.21s
54:	learn: 0.1269231	total: 967ms	remaining: 4.31s
47:	learn: 0.1259576	total: 790ms	remaining: 4.15s
51:	learn: 0.1262880	total: 957ms	remaining: 4.56s
55:	learn: 0.1232269	total: 998ms	remaining: 4.35s
56:	learn: 0.1268091	total: 1.09s	remaining: 4.63s
57:	learn: 0.1266432	total: 1.09s	remaining: 4.55s
56:	learn: 0.1230659	total: 1s	remaining: 4.27s
48:	learn: 0.1257185	total: 799ms	remaining: 4.09s
55:	learn: 0.1267245	total: 983ms	remaining: 4.28s
58:	learn: 0.1265024	total: 1.1s	remaining: 4.48s
52:	learn: 0.1260765	total: 975ms	remaining: 4.54s
53:	learn: 0.1258724	total: 982ms	remaining: 4.47s
49:	learn: 0.1255005	total: 818ms	remaining: 4.09s
57:	learn: 0.1229525	total: 1.02s	remaining: 4.28s
58:	learn: 0.1228311	total: 1.03s	remaining: 4.21s
50:	learn: 0.1252800	total: 828ms	remaining: 4.04s
59:	learn: 0.1227166	total: 1.03s	remaining: 4.14s
56:	learn: 0.1266112	total: 1.01s	remaining: 4.31s
57:	learn: 0.1264006	total: 1.02s	remaining: 4.26s
54:	learn: 0.1256934	total: 1.01s	remaining: 4.5s
55:	learn: 0.1255372	total: 1.02s	remaining: 4.43s
51:	learn: 0.1250786	total: 854ms	remaining: 4.07s
58:	learn: 0.1262785	total: 1.04s	remaining: 4.24s
59:	learn: 0.1263997	total: 1.15s	remaining: 4.61s
52:	learn: 0.1248472	total: 863ms	remaining: 4.02s
59:	learn: 0.1261836	total: 1.05s	remaining: 4.19s
60:	learn: 0.1263363	total: 1.16s	remaining: 4.54s
60:	learn: 0.1226436	total: 1.07s	remaining: 4.21s
60:	learn: 0.1260553	total: 1.05s	remaining: 4.13s
56:	learn: 0.1254217	total: 1.04s	remaining: 4.43s
53:	learn: 0.1246216	total: 882ms	remaining: 4.01s
57:	learn: 0.1252665	total: 1.05s	remaining: 4.38s
61:	learn: 0.1262365	total: 1.18s	remaining: 4.54s
54:	learn: 0.1244407	total: 889ms	remaining: 3.96s
61:	learn: 0.1225587	total: 1.1s	remaining: 4.22s
61:	learn: 0.1258974	total: 1.08s	remaining: 4.14s
62:	learn: 0.1261214	total: 1.19s	remaining: 4.49s
62:	learn: 0.1224768	total: 1.11s	remaining: 4.16s
58:	learn: 0.1251504	total: 1.07s	remaining: 4.38s
63:	learn: 0.1259960	total: 1.2s	remaining: 4.44s
55:	learn: 0.1242837	total: 911ms	remaining: 3.97s
63:	learn: 0.1223969	total: 1.12s	remaining: 4.13s
62:	learn: 0.1257568	total: 1.1s	remaining: 4.13s
59:	learn: 0.1250285	total: 1.09s	remaining: 4.34s
64:	learn: 0.1259025	total: 1.22s	remaining: 4.4s
64:	learn: 0.1222687	total: 1.13s	remaining: 4.1s
60:	learn: 0.1249254	total: 1.1s	remaining: 4.31s
63:	learn: 0.1256177	total: 1.12s	remaining: 4.13s
61:	learn: 0.1247577	total: 1.11s	remaining: 4.26s
56:	learn: 0.1241451	total: 946ms	remaining: 4.03s
65:	learn: 0.1258204	total: 1.24s	remaining: 4.4s
62:	learn: 0.1246598	total: 1.12s	remaining: 4.2s
57:	learn: 0.1240208	total: 955ms	remaining: 3.98s
65:	learn: 0.1221466	total: 1.16s	remaining: 4.12s
58:	learn: 0.1238791	total: 960ms	remaining: 3.92s
64:	learn: 0.1255142	total: 1.15s	remaining: 4.15s
66:	learn: 0.1257275	total: 1.26s	remaining: 4.4s
59:	learn: 0.1237680	total: 975ms	remaining: 3.9s
65:	learn: 0.1254262	total: 1.16s	remaining: 4.11s
67:	learn: 0.1256418	total: 1.27s	remaining: 4.33s
63:	learn: 0.1245486	total: 1.15s	remaining: 4.23s
66:	learn: 0.1253464	total: 1.17s	remaining: 4.06s
66:	learn: 0.1220871	total: 1.19s	remaining: 4.14s
68:	learn: 0.1255598	total: 1.29s	remaining: 4.31s
60:	learn: 0.1236368	total: 997ms	remaining: 3.91s
67:	learn: 0.1252637	total: 1.18s	remaining: 4.04s
61:	learn: 0.1235363	total: 1s	remaining: 3.85s
67:	learn: 0.1219961	total: 1.21s	remaining: 4.12s
68:	learn: 0.1251623	total: 1.19s	remaining: 3.98s
64:	learn: 0.1243996	total: 1.17s	remaining: 4.25s
69:	learn: 0.1254649	total: 1.3s	remaining: 4.29s
68:	learn: 0.1218504	total: 1.22s	remaining: 4.08s
65:	learn: 0.1243011	total: 1.19s	remaining: 4.22s
70:	learn: 0.1253671	total: 1.32s	remaining: 4.25s
69:	learn: 0.1250921	total: 1.21s	remaining: 3.97s
66:	learn: 0.1241626	total: 1.2s	remaining: 4.16s

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

183:	learn: 0.1161562	total: 2.65s	remaining: 1.67s
180:	learn: 0.1183599	total: 2.6s	remaining: 1.71s
178:	learn: 0.1172819	total: 2.44s	remaining: 1.65s
181:	learn: 0.1200762	total: 2.75s	remaining: 1.78s
184:	learn: 0.1161327	total: 2.65s	remaining: 1.65s
179:	learn: 0.1172426	total: 2.44s	remaining: 1.63s
181:	learn: 0.1183292	total: 2.61s	remaining: 1.69s
182:	learn: 0.1200380	total: 2.76s	remaining: 1.76s
185:	learn: 0.1161024	total: 2.66s	remaining: 1.63s
183:	learn: 0.1198948	total: 2.64s	remaining: 1.66s
182:	learn: 0.1182832	total: 2.62s	remaining: 1.68s
183:	learn: 0.1200040	total: 2.77s	remaining: 1.74s
180:	learn: 0.1172180	total: 2.46s	remaining: 1.62s
186:	learn: 0.1160752	total: 2.67s	remaining: 1.61s
184:	learn: 0.1198389	total: 2.65s	remaining: 1.65s
181:	learn: 0.1171859	total: 2.46s	remaining: 1.6s
183:	learn: 0.1182280	total: 2.63s	remaining: 1.66s
185:	learn: 0.1198097	total: 2.65s	remaining: 1.62s
184:	learn: 0.1199706	total: 2.77s	remaining: 1.73s
187:	learn: 0.1160478	total: 2.68s	remaining: 1.6s
186:	learn: 0.1197345	total: 2.66s	remaining: 1.61s
188:	learn: 0.1160078	total: 2.69s	remaining: 1.58s
185:	learn: 0.1199286	total: 2.79s	remaining: 1.71s
184:	learn: 0.1181929	total: 2.65s	remaining: 1.64s
182:	learn: 0.1171542	total: 2.48s	remaining: 1.59s
187:	learn: 0.1196990	total: 2.67s	remaining: 1.59s
185:	learn: 0.1181587	total: 2.65s	remaining: 1.62s
189:	learn: 0.1159841	total: 2.69s	remaining: 1.56s
186:	learn: 0.1199125	total: 2.79s	remaining: 1.69s
190:	learn: 0.1159483	total: 2.7s	remaining: 1.54s
183:	learn: 0.1171225	total: 2.49s	remaining: 1.57s
187:	learn: 0.1198951	total: 2.8s	remaining: 1.67s
184:	learn: 0.1170889	total: 2.49s	remaining: 1.55s
186:	learn: 0.1181206	total: 2.66s	remaining: 1.61s
188:	learn: 0.1198702	total: 2.81s	remaining: 1.65s
188:	learn: 0.1196525	total: 2.68s	remaining: 1.58s
191:	learn: 0.1159241	total: 2.71s	remaining: 1.52s
187:	learn: 0.1180914	total: 2.66s	remaining: 1.59s
189:	learn: 0.1196180	total: 2.69s	remaining: 1.55s
185:	learn: 0.1170384	total: 2.5s	remaining: 1.53s
189:	learn: 0.1198393	total: 2.81s	remaining: 1.63s
188:	learn: 0.1180758	total: 2.67s	remaining: 1.57s
190:	learn: 0.1195878	total: 2.69s	remaining: 1.53s
192:	learn: 0.1158952	total: 2.71s	remaining: 1.5s
190:	learn: 0.1198136	total: 2.81s	remaining: 1.61s
186:	learn: 0.1169643	total: 2.5s	remaining: 1.51s
191:	learn: 0.1195648	total: 2.69s	remaining: 1.51s
189:	learn: 0.1180091	total: 2.67s	remaining: 1.55s
187:	learn: 0.1169051	total: 2.5s	remaining: 1.49s
192:	learn: 0.1195356	total: 2.7s	remaining: 1.49s
193:	learn: 0.1158790	total: 2.72s	remaining: 1.49s
190:	learn: 0.1179905	total: 2.68s	remaining: 1.53s
191:	learn: 0.1197704	total: 2.83s	remaining: 1.59s
193:	learn: 0.1195138	total: 2.7s	remaining: 1.48s
191:	learn: 0.1179697	total: 2.69s	remaining: 1.51s
188:	learn: 0.1168647	total: 2.52s	remaining: 1.48s
194:	learn: 0.1194813	total: 2.71s	remaining: 1.46s
192:	learn: 0.1197492	total: 2.83s	remaining: 1.57s
194:	learn: 0.1158297	total: 2.73s	remaining: 1.47s
192:	learn: 0.1179466	total: 2.69s	remaining: 1.49s
189:	learn: 0.1168241	total: 2.52s	remaining: 1.46s
195:	learn: 0.1194766	total: 2.71s	remaining: 1.44s
195:	learn: 0.1158120	total: 2.74s	remaining: 1.45s
193:	learn: 0.1197258	total: 2.84s	remaining: 1.55s
190:	learn: 0.1168060	total: 2.52s	remaining: 1.44s
196:	learn: 0.1194346	total: 2.72s	remaining: 1.42s
193:	learn: 0.1179188	total: 2.69s	remaining: 1.47s
197:	learn: 0.1193864	total: 2.72s	remaining: 1.4s
194:	learn: 0.1196945	total: 2.84s	remaining: 1.53s
196:	learn: 0.1157863	total: 2.74s	remaining: 1.43s
194:	learn: 0.1178907	total: 2.7s	remaining: 1.45s
191:	learn: 0.1167885	total: 2.53s	remaining: 1.42s
195:	learn: 0.1196545	total: 2.84s	remaining: 1.51s
198:	learn: 0.1193330	total: 2.72s	remaining: 1.38s
195:	learn: 0.1178397	total: 2.7s	remaining: 1.43s
192:	learn: 0.1167623	total: 2.54s	remaining: 1.41s
196:	learn: 0.1196206	total: 2.85s	remaining: 1.49s
196:	learn: 0.1178039	total: 2.71s	remaining: 1.42s
199:	learn: 0.1192476	total: 2.73s	remaining: 1.36s
193:	learn: 0.1166924	total: 2.54s	remaining: 1.39s
197:	learn: 0.1195959	total: 2.85s	remaining: 1.47s
197:	learn: 0.1177739	total: 2.71s	remaining: 1.4s
200:	learn: 0.1191969	total: 2.73s	remaining: 1.35s
198:	learn: 0.1177477	total: 2.71s	remaining: 1.38s
201:	learn: 0.1191199	total: 2.74s	remaining: 1.33s
199:	learn: 0.1177192	total: 2.72s	remaining: 1.36s
197:	learn: 0.1157636	total: 2.76s	remaining: 1.42s
194:	learn: 0.1166540	total: 2.55s	remaining: 1.37s
202:	learn: 0.1190888	total: 2.74s	remaining: 1.31s
200:	learn: 0.1176885	total: 2.72s	remaining: 1.34s
198:	learn: 0.1195617	total: 2.87s	remaining: 1.46s
198:	learn: 0.1157395	total: 2.77s	remaining: 1.41s
195:	learn: 0.1166193	total: 2.56s	remaining: 1.36s
201:	learn: 0.1176583	total: 2.73s	remaining: 1.32s
199:	learn: 0.1194917	total: 2.87s	remaining: 1.44s
199:	learn: 0.1157085	total: 2.77s	remaining: 1.39s
203:	learn: 0.1190402	total: 2.75s	remaining: 1.29s
196:	learn: 0.1165971	total: 2.56s	remaining: 1.34s
202:	learn: 0.1176325	total: 2.73s	remaining: 1.3s
200:	learn: 0.1194422	total: 2.87s	remaining: 1.42s
197:	learn: 0.1165516	total: 2.56s	remaining: 1.32s
200:	learn: 0.1156895	total: 2.78s	remaining: 1.37s
203:	learn: 0.1176003	total: 2.73s	remaining: 1.29s
204:	learn: 0.1189813	total: 2.75s	remaining: 1.28s
201:	learn: 0.1194040	total: 2.88s	remaining: 1.4s
198:	learn: 0.1165127	total: 2.57s	remaining: 1.3s
201:	learn: 0.1156631	total: 2.78s	remaining: 1.35s
204:	learn: 0.1175678	total: 2.74s	remaining: 1.27s
202:	learn: 0.1193705	total: 2.88s	remaining: 1.38s
202:	learn: 0.1156218	total: 2.78s	remaining: 1.33s
205:	learn: 0.1189387	total: 2.76s	remaining: 1.26s
199:	learn: 0.1164714	total: 2.57s	remaining: 1.29s
205:	learn: 0.1175411	total: 2.74s	remaining: 1.25s
203:	learn: 0.1193275	total: 2.89s	remaining: 1.36s
203:	learn: 0.1156003	total: 2.79s	remaining: 1.31s
206:	learn: 0.1189019	total: 2.76s	remaining: 1.24s
200:	learn: 0.1164333	total: 2.58s	remaining: 1.27s
207:	learn: 0.1188645	total: 2.77s	remaining: 1.22s
204:	learn: 0.1193020	total: 2.89s	remaining: 1.34s
204:	learn: 0.1155696	total: 2.79s	remaining: 1.29s
206:	learn: 0.1174744	total: 2.75s	remaining: 1.23s
208:	learn: 0.1188348	total: 2.77s	remaining: 1.21s
205:	learn: 0.1155409	total: 2.79s	remaining: 1.27s
205:	learn: 0.1192519	total: 2.9s	remaining: 1.32s
207:	learn: 0.1174293	total: 2.75s	remaining: 1.22s
201:	learn: 0.1164011	total: 2.58s	remaining: 1.25s
206:	learn: 0.1155059	total: 2.8s	remaining: 1.26s
209:	learn: 0.1188036	total: 2.77s	remaining: 1.19s
202:	learn: 0.1163566	total: 2.59s	remaining: 1.24s
208:	learn: 0.1173919	total: 2.75s	remaining: 1.2s
206:	learn: 0.1192280	total: 2.9s	remaining: 1.3s
207:	learn: 0.1154381	total: 2.8s	remaining: 1.24s
209:	learn: 0.1173600	total: 2.76s	remaining: 1.18s
210:	learn: 0.1187755	total: 2.78s	remaining: 1.17s
203:	learn: 0.1163177	total: 2.59s	remaining: 1.22s
208:	learn: 0.1153987	total: 2.8s	remaining: 1.22s
207:	learn: 0.1191827	total: 2.9s	remaining: 1.28s
211:	learn: 0.1187555	total: 2.78s	remaining: 1.16s
210:	learn: 0.1173067	total: 2.76s	remaining: 1.17s
208:	learn: 0.1191620	total: 2.91s	remaining: 1.26s
204:	learn: 0.1162920	total: 2.6s	remaining: 1.2s
209:	learn: 0.1153254	total: 2.81s	remaining: 1.2s
212:	learn: 0.1187230	total: 2.79s	remaining: 1.14s
210:	learn: 0.1152936	total: 2.81s	remaining: 1.19s
209:	learn: 0.1191315	total: 2.91s	remaining: 1.25s
211:	learn: 0.1172799	total: 2.77s	remaining: 1.15s
205:	learn: 0.1162450	total: 2.6s	remaining: 1.19s
213:	learn: 0.1186997	total: 2.79s	remaining: 1.12s
211:	learn: 0.1152619	total: 2.81s	remaining: 1.17s
210:	learn: 0.1190812	total: 2.92s	remaining: 1.23s
212:	learn: 0.1172511	total: 2.77s	remaining: 1.13s
206:	learn: 0.1162049	total: 2.6s	remaining: 1.17s
211:	learn: 0.1190562	total: 2.92s	remaining: 1.21s
214:	learn: 0.1186497	total: 2.79s	remaining: 1.1s
212:	learn: 0.1152071	total: 2.82s	remaining: 1.15s
213:	learn: 0.1172041	total: 2.78s	remaining: 1.11s
207:	learn: 0.1161836	total: 2.61s	remaining: 1.15s
212:	learn: 0.1190051	total: 2.92s	remaining: 1.19s
215:	learn: 0.1186053	total: 2.8s	remaining: 1.09s
208:	learn: 0.1161597	total: 2.61s	remaining: 1.14s
214:	learn: 0.1171694	total: 2.78s	remaining: 1.1s
213:	learn: 0.1189867	total: 2.92s	remaining: 1.18s
213:	learn: 0.1151604	total: 2.82s	remaining: 1.14s
215:	learn: 0.1171347	total: 2.78s	remaining: 1.08s
214:	learn: 0.1189329	total: 2.93s	remaining: 1.16s
209:	learn: 0.1161248	total: 2.62s	remaining: 1.12s
216:	learn: 0.1185691	total: 2.8s	remaining: 1.07s
214:	learn: 0.1151381	total: 2.83s	remaining: 1.12s
216:	learn: 0.1171035	total: 2.79s	remaining: 1.06s
210:	learn: 0.1161031	total: 2.62s	remaining: 1.1s
215:	learn: 0.1188827	total: 2.93s	remaining: 1.14s
215:	learn: 0.1151157	total: 2.83s	remaining: 1.1s
217:	learn: 0.1170697	total: 2.79s	remaining: 1.05s
217:	learn: 0.1185496	total: 2.81s	remaining: 1.06s
211:	learn: 0.1160426	total: 2.62s	remaining: 1.09s
216:	learn: 0.1188462	total: 2.94s	remaining: 1.12s
218:	learn: 0.1170422	total: 2.79s	remaining: 1.03s
216:	learn: 0.1150945	total: 2.84s	remaining: 1.08s
212:	learn: 0.1159885	total: 2.62s	remaining: 1.07s
218:	learn: 0.1185123	total: 2.81s	remaining: 1.04s
217:	learn: 0.1188059	total: 2.94s	remaining: 1.1s
219:	learn: 0.1170167	total: 2.79s	remaining: 1.02s
219:	learn: 0.1184860	total: 2.82s	remaining: 1.02s
217:	learn: 0.1150597	total: 2.84s	remaining: 1.07s
213:	learn: 0.1159616	total: 2.63s	remaining: 1.06s
218:	learn: 0.1187662	total: 2.94s	remaining: 1.09s
214:	learn: 0.1159280	total: 2.63s	remaining: 1.04s
218:	learn: 0.1150213	total: 2.84s	remaining: 1.05s
220:	learn: 0.1169866	total: 2.8s	remaining: 1s
220:	learn: 0.1184696	total: 2.82s	remaining: 1.01s
219:	learn: 0.1150030	total: 2.85s	remaining: 1.03s

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

215:	learn: 0.1158692	total: 2.63s	remaining: 1.02s
221:	learn: 0.1169545	total: 2.8s	remaining: 985ms
219:	learn: 0.1187417	total: 2.95s	remaining: 1.07s
221:	learn: 0.1184372	total: 2.82s	remaining: 992ms
222:	learn: 0.1169233	total: 2.81s	remaining: 969ms
220:	learn: 0.1149854	total: 2.85s	remaining: 1.02s
216:	learn: 0.1158225	total: 2.64s	remaining: 1.01s
220:	learn: 0.1187081	total: 2.95s	remaining: 1.05s
222:	learn: 0.1184127	total: 2.83s	remaining: 977ms
221:	learn: 0.1149636	total: 2.85s	remaining: 1s
217:	learn: 0.1157927	total: 2.64s	remaining: 993ms
223:	learn: 0.1168845	total: 2.81s	remaining: 953ms
223:	learn: 0.1183749	total: 2.83s	remaining: 960ms
222:	learn: 0.1149276	total: 2.85s	remaining: 986ms
221:	learn: 0.1186453	total: 2.96s	remaining: 1.04s
218:	learn: 0.1157278	total: 2.64s	remaining: 978ms
224:	learn: 0.1168591	total: 2.81s	remaining: 938ms
224:	learn: 0.1183310	total: 2.83s	remaining: 945ms
223:	learn: 0.1149057	total: 2.86s	remaining: 970ms
222:	learn: 0.1186130	total: 2.96s	remaining: 1.02s
225:	learn: 0.1168038	total: 2.82s	remaining: 922ms
219:	learn: 0.1156965	total: 2.65s	remaining: 964ms
225:	learn: 0.1182742	total: 2.84s	remaining: 930ms
224:	learn: 0.1148744	total: 2.86s	remaining: 955ms
223:	learn: 0.1185722	total: 2.96s	remaining: 1s
226:	learn: 0.1167631	total: 2.82s	remaining: 907ms
220:	learn: 0.1156744	total: 2.65s	remaining: 948ms
226:	learn: 0.1182492	total: 2.84s	remaining: 914ms
225:	learn: 0.1148310	total: 2.87s	remaining: 939ms
224:	learn: 0.1185443	total: 2.97s	remaining: 989ms
227:	learn: 0.1167217	total: 2.82s	remaining: 892ms
226:	learn: 0.1148040	total: 2.87s	remaining: 923ms
221:	learn: 0.1156384	total: 2.66s	remaining: 934ms
225:	learn: 0.1184828	total: 2.97s	remaining: 973ms
228:	learn: 0.1167004	total: 2.83s	remaining: 877ms
227:	learn: 0.1182264	total: 2.85s	remaining: 899ms
227:	learn: 0.1147701	total: 2.87s	remaining: 908ms
222:	learn: 0.1156189	total: 2.66s	remaining: 919ms
228:	learn: 0.1181889	total: 2.85s	remaining: 884ms
229:	learn: 0.1166636	total: 2.83s	remaining: 862ms
226:	learn: 0.1184184	total: 2.98s	remaining: 957ms
228:	learn: 0.1147435	total: 2.88s	remaining: 892ms
223:	learn: 0.1155828	total: 2.67s	remaining: 905ms
229:	learn: 0.1181603	total: 2.85s	remaining: 869ms
230:	learn: 0.1166501	total: 2.84s	remaining: 847ms
227:	learn: 0.1183870	total: 2.98s	remaining: 941ms
229:	learn: 0.1147070	total: 2.88s	remaining: 877ms
224:	learn: 0.1155290	total: 2.67s	remaining: 890ms
231:	learn: 0.1166209	total: 2.84s	remaining: 832ms
228:	learn: 0.1183533	total: 2.98s	remaining: 925ms
230:	learn: 0.1181179	total: 2.86s	remaining: 855ms
230:	learn: 0.1146899	total: 2.88s	remaining: 862ms
225:	learn: 0.1155094	total: 2.67s	remaining: 876ms
232:	learn: 0.1165785	total: 2.84s	remaining: 817ms
231:	learn: 0.1146502	total: 2.89s	remaining: 847ms
229:	learn: 0.1182970	total: 2.99s	remaining: 909ms
231:	learn: 0.1180913	total: 2.87s	remaining: 840ms
226:	learn: 0.1154844	total: 2.68s	remaining: 861ms
232:	learn: 0.1146014	total: 2.89s	remaining: 831ms
230:	learn: 0.1182648	total: 2.99s	remaining: 893ms
233:	learn: 0.1165516	total: 2.85s	remaining: 803ms
232:	learn: 0.1180705	total: 2.87s	remaining: 825ms
233:	learn: 0.1145580	total: 2.89s	remaining: 816ms
227:	learn: 0.1154564	total: 2.68s	remaining: 847ms
234:	learn: 0.1164766	total: 2.85s	remaining: 789ms
231:	learn: 0.1182428	total: 3s	remaining: 878ms
234:	learn: 0.1145335	total: 2.9s	remaining: 801ms
233:	learn: 0.1180519	total: 2.87s	remaining: 810ms
228:	learn: 0.1154295	total: 2.68s	remaining: 832ms
235:	learn: 0.1144645	total: 2.9s	remaining: 786ms
235:	learn: 0.1164598	total: 2.85s	remaining: 774ms
232:	learn: 0.1182224	total: 3s	remaining: 862ms
229:	learn: 0.1154036	total: 2.69s	remaining: 818ms
234:	learn: 0.1179895	total: 2.88s	remaining: 796ms
236:	learn: 0.1144290	total: 2.9s	remaining: 771ms
233:	learn: 0.1181839	total: 3s	remaining: 847ms
236:	learn: 0.1164361	total: 2.86s	remaining: 760ms
230:	learn: 0.1153844	total: 2.69s	remaining: 804ms
235:	learn: 0.1179671	total: 2.88s	remaining: 781ms
237:	learn: 0.1144031	total: 2.9s	remaining: 757ms
237:	learn: 0.1164173	total: 2.86s	remaining: 746ms
234:	learn: 0.1181434	total: 3.01s	remaining: 832ms
231:	learn: 0.1153648	total: 2.69s	remaining: 790ms
236:	learn: 0.1179345	total: 2.88s	remaining: 767ms
238:	learn: 0.1143656	total: 2.91s	remaining: 742ms
238:	learn: 0.1163850	total: 2.86s	remaining: 731ms
235:	learn: 0.1181207	total: 3.01s	remaining: 816ms
232:	learn: 0.1153489	total: 2.7s	remaining: 776ms
239:	learn: 0.1163621	total: 2.87s	remaining: 717ms
237:	learn: 0.1178778	total: 2.89s	remaining: 752ms
239:	learn: 0.1143448	total: 2.91s	remaining: 728ms
233:	learn: 0.1153305	total: 2.7s	remaining: 762ms
236:	learn: 0.1180879	total: 3.01s	remaining: 801ms
240:	learn: 0.1163407	total: 2.87s	remaining: 703ms
238:	learn: 0.1178438	total: 2.89s	remaining: 738ms
240:	learn: 0.1142924	total: 2.92s	remaining: 714ms
237:	learn: 0.1180693	total: 3.02s	remaining: 786ms
234:	learn: 0.1152770	total: 2.71s	remaining: 748ms
241:	learn: 0.1163054	total: 2.87s	remaining: 689ms
241:	learn: 0.1142389	total: 2.92s	remaining: 700ms
239:	learn: 0.1177922	total: 2.9s	remaining: 724ms
238:	learn: 0.1180200	total: 3.02s	remaining: 771ms
235:	learn: 0.1152319	total: 2.71s	remaining: 735ms
242:	learn: 0.1162858	total: 2.88s	remaining: 675ms
240:	learn: 0.1177615	total: 2.9s	remaining: 709ms
242:	learn: 0.1142180	total: 2.92s	remaining: 686ms
243:	learn: 0.1162496	total: 2.88s	remaining: 661ms
241:	learn: 0.1177261	total: 2.9s	remaining: 695ms
239:	learn: 0.1179854	total: 3.02s	remaining: 756ms
236:	learn: 0.1152177	total: 2.71s	remaining: 721ms
243:	learn: 0.1141771	total: 2.92s	remaining: 671ms
240:	learn: 0.1179614	total: 3.03s	remaining: 741ms
244:	learn: 0.1162150	total: 2.88s	remaining: 647ms
242:	learn: 0.1176898	total: 2.9s	remaining: 681ms
244:	learn: 0.1141563	total: 2.93s	remaining: 658ms
237:	learn: 0.1151763	total: 2.72s	remaining: 708ms
241:	learn: 0.1179363	total: 3.03s	remaining: 726ms
243:	learn: 0.1176528	total: 2.91s	remaining: 667ms
245:	learn: 0.1161925	total: 2.89s	remaining: 634ms
245:	learn: 0.1140965	total: 2.93s	remaining: 644ms
238:	learn: 0.1151438	total: 2.72s	remaining: 694ms
242:	learn: 0.1179003	total: 3.03s	remaining: 712ms
246:	learn: 0.1161591	total: 2.89s	remaining: 620ms
244:	learn: 0.1176280	total: 2.91s	remaining: 654ms
246:	learn: 0.1140775	total: 2.94s	remaining: 630ms
239:	learn: 0.1151256	total: 2.72s	remaining: 681ms
243:	learn: 0.1178775	total: 3.04s	remaining: 697ms
247:	learn: 0.1140201	total: 2.94s	remaining: 616ms
247:	learn: 0.1161130	total: 2.89s	remaining: 607ms
245:	learn: 0.1175922	total: 2.92s	remaining: 640ms
240:	learn: 0.1150951	total: 2.73s	remaining: 668ms
244:	learn: 0.1178324	total: 3.04s	remaining: 683ms
248:	learn: 0.1140010	total: 2.94s	remaining: 603ms
248:	learn: 0.1160683	total: 2.9s	remaining: 594ms
246:	learn: 0.1175634	total: 2.92s	remaining: 626ms
249:	learn: 0.1139512	total: 2.94s	remaining: 589ms
245:	learn: 0.1177970	total: 3.04s	remaining: 668ms
241:	learn: 0.1150602	total: 2.73s	remaining: 655ms
247:	learn: 0.1175263	total: 2.92s	remaining: 613ms
249:	learn: 0.1160267	total: 2.9s	remaining: 580ms
250:	learn: 0.1139312	total: 2.95s	remaining: 575ms
246:	learn: 0.1177721	total: 3.05s	remaining: 654ms
242:	learn: 0.1150285	total: 2.74s	remaining: 642ms
250:	learn: 0.1159675	total: 2.9s	remaining: 567ms
248:	learn: 0.1174932	total: 2.93s	remaining: 599ms
251:	learn: 0.1138672	total: 2.95s	remaining: 562ms
243:	learn: 0.1150014	total: 2.74s	remaining: 629ms
247:	learn: 0.1177193	total: 3.05s	remaining: 640ms
251:	learn: 0.1159339	total: 2.91s	remaining: 554ms
249:	learn: 0.1174629	total: 2.93s	remaining: 586ms
252:	learn: 0.1138353	total: 2.95s	remaining: 549ms
244:	learn: 0.1149846	total: 2.74s	remaining: 616ms
248:	learn: 0.1176914	total: 3.06s	remaining: 626ms
252:	learn: 0.1159002	total: 2.91s	remaining: 541ms
249:	learn: 0.1176687	total: 3.06s	remaining: 612ms
245:	learn: 0.1149597	total: 2.75s	remaining: 603ms
250:	learn: 0.1174157	total: 2.94s	remaining: 573ms
253:	learn: 0.1137993	total: 2.96s	remaining: 536ms
253:	learn: 0.1158740	total: 2.92s	remaining: 529ms
251:	learn: 0.1173883	total: 2.94s	remaining: 560ms
246:	learn: 0.1149372	total: 2.75s	remaining: 591ms
254:	learn: 0.1137742	total: 2.96s	remaining: 523ms
254:	learn: 0.1158342	total: 2.92s	remaining: 516ms
252:	learn: 0.1173571	total: 2.94s	remaining: 547ms
247:	learn: 0.1148874	total: 2.75s	remaining: 578ms
250:	learn: 0.1176215	total: 3.07s	remaining: 599ms
255:	learn: 0.1137149	total: 2.97s	remaining: 510ms
255:	learn: 0.1158144	total: 2.93s	remaining: 503ms
253:	learn: 0.1173142	total: 2.95s	remaining: 534ms
251:	learn: 0.1175907	total: 3.07s	remaining: 585ms
248:	learn: 0.1148152	total: 2.76s	remaining: 565ms
256:	learn: 0.1136611	total: 2.97s	remaining: 497ms
256:	learn: 0.1157752	total: 2.93s	remaining: 490ms
254:	learn: 0.1172844	total: 2.95s	remaining: 521ms
252:	learn: 0.1175736	total: 3.07s	remaining: 571ms
249:	learn: 0.1147557	total: 2.76s	remaining: 553ms
257:	learn: 0.1136304	total: 2.98s	remaining: 485ms
257:	learn: 0.1157350	total: 2.93s	remaining: 478ms
253:	learn: 0.1175197	total: 3.08s	remaining: 558ms
250:	learn: 0.1147274	total: 2.77s	remaining: 540ms
255:	learn: 0.1172544	total: 2.96s	remaining: 508ms
258:	learn: 0.1135979	total: 2.98s	remaining: 472ms
258:	learn: 0.1157159	total: 2.94s	remaining: 465ms
254:	learn: 0.1175009	total: 3.08s	remaining: 544ms
256:	learn: 0.1172276	total: 2.96s	remaining: 495ms
251:	learn: 0.1146731	total: 2.77s	remaining: 528ms
259:	learn: 0.1156836	total: 2.94s	remaining: 452ms
259:	learn: 0.1135700	total: 2.98s	remaining: 459ms
252:	learn: 0.1146531	total: 2.77s	remaining: 515ms
257:	learn: 0.1172033	total: 2.96s	remaining: 482ms
260:	learn: 0.1135421	total: 2.99s	remaining: 446ms
260:	learn: 0.1156676	total: 2.94s	remaining: 440ms
255:	learn: 0.1174556	total: 3.09s	remaining: 531ms
253:	learn: 0.1146365	total: 2.78s	remaining: 503ms
261:	learn: 0.1135033	total: 2.99s	remaining: 434ms
258:	learn: 0.1171780	total: 2.97s	remaining: 470ms
254:	learn: 0.1146037	total: 2.78s	remaining: 491ms
261:	learn: 0.1156365	total: 2.95s	remaining: 428ms
262:	learn: 0.1134622	total: 2.99s	remaining: 421ms
256:	learn: 0.1174304	total: 3.09s	remaining: 518ms
259:	learn: 0.1171465	total: 2.97s	remaining: 457ms
255:	learn: 0.1145539	total: 2.78s	remaining: 478ms
263:	learn: 0.1134281	total: 3s	remaining: 409ms
262:	learn: 0.1156156	total: 2.95s	remaining: 415ms
257:	learn: 0.1174022	total: 3.1s	remaining: 504ms
256:	learn: 0.1145251	total: 2.79s	remaining: 466ms
260:	learn: 0.1171282	total: 2.97s	remaining: 445ms
263:	learn: 0.1155991	total: 2.96s	remaining: 403ms
264:	learn: 0.1134137	total: 3s	remaining: 396ms
258:	learn: 0.1173765	total: 3.1s	remaining: 491ms
257:	learn: 0.1145095	total: 2.79s	remaining: 454ms
261:	learn: 0.1170893	total: 2.98s	remaining: 432ms
265:	learn: 0.1133706	total: 3s	remaining: 384ms
264:	learn: 0.1155761	total: 2.96s	remaining: 391ms
259:	learn: 0.1173511	total: 3.1s	remaining: 478ms
258:	learn: 0.1144748	total: 2.79s	remaining: 442ms
266:	learn: 0.1133494	total: 3s	remaining: 371ms
262:	learn: 0.1170804	total: 2.98s	remaining: 420ms
265:	learn: 0.1155403	total: 2.96s	remaining: 379ms
259:	learn: 0.1144483	total: 2.79s	remaining: 430ms
260:	learn: 0.1173151	total: 3.11s	remaining: 464ms
263:	learn: 0.1170613	total: 2.98s	remaining: 407ms
267:	learn: 0.1133158	total: 3.01s	remaining: 359ms
266:	learn: 0.1155210	total: 2.97s	remaining: 367ms
260:	learn: 0.1144237	total: 2.8s	remaining: 418ms
261:	learn: 0.1172870	total: 3.11s	remaining: 451ms
264:	learn: 0.1170409	total: 2.99s	remaining: 395ms
268:	learn: 0.1132842	total: 3.01s	remaining: 347ms
267:	learn: 0.1154926	total: 2.97s	remaining: 355ms
261:	learn: 0.1143916	total: 2.8s	remaining: 406ms
262:	learn: 0.1172489	total: 3.12s	remaining: 438ms
265:	learn: 0.1170015	total: 2.99s	remaining: 383ms
269:	learn: 0.1132464	total: 3.02s	remaining: 335ms
262:	learn: 0.1143674	total: 2.8s	remaining: 395ms
268:	learn: 0.1154063	total: 2.97s	remaining: 343ms
263:	learn: 0.1172258	total: 3.12s	remaining: 425ms
266:	learn: 0.1169827	total: 3s	remaining: 370ms
270:	learn: 0.1132075	total: 3.02s	remaining: 323ms
269:	learn: 0.1153919	total: 2.98s	remaining: 331ms
263:	learn: 0.1143458	total: 2.81s	remaining: 383ms
264:	learn: 0.1171870	total: 3.12s	remaining: 412ms
271:	learn: 0.1131731	total: 3.02s	remaining: 311ms
264:	learn: 0.1143307	total: 2.81s	remaining: 371ms
265:	learn: 0.1171665	total: 3.12s	remaining: 399ms
267:	learn: 0.1169609	total: 3s	remaining: 358ms
270:	learn: 0.1153527	total: 2.98s	remaining: 319ms
265:	learn: 0.1143013	total: 2.81s	remaining: 360ms
272:	learn: 0.1131570	total: 3.03s	remaining: 299ms
266:	learn: 0.1171352	total: 3.13s	remaining: 387ms
268:	learn: 0.1169371	total: 3s	remaining: 346ms
266:	learn: 0.1142734	total: 2.82s	remaining: 348ms
271:	learn: 0.1153269	total: 2.99s	remaining: 307ms
273:	learn: 0.1131213	total: 3.03s	remaining: 288ms
267:	learn: 0.1171006	total: 3.13s	remaining: 374ms
269:	learn: 0.1168901	total: 3.01s	remaining: 334ms
272:	learn: 0.1152754	total: 2.99s	remaining: 296ms
267:	learn: 0.1142294	total: 2.82s	remaining: 337ms
268:	learn: 0.1170497	total: 3.13s	remaining: 361ms
274:	learn: 0.1131065	total: 3.03s	remaining: 276ms
275:	learn: 0.1130809	total: 3.04s	remaining: 264ms
270:	learn: 0.1168633	total: 3.01s	remaining: 323ms
268:	learn: 0.1142072	total: 2.83s	remaining: 326ms
273:	learn: 0.1152433	total: 2.99s	remaining: 284ms
269:	learn: 0.1170157	total: 3.14s	remaining: 349ms
269:	learn: 0.1141751	total: 2.83s	remaining: 314ms
271:	learn: 0.1168499	total: 3.02s	remaining: 311ms
276:	learn: 0.1130553	total: 3.04s	remaining: 252ms
274:	learn: 0.1152210	total: 3s	remaining: 272ms
270:	learn: 0.1169747	total: 3.14s	remaining: 336ms
270:	learn: 0.1140957	total: 2.83s	remaining: 303ms
272:	learn: 0.1168373	total: 3.02s	remaining: 299ms
271:	learn: 0.1169356	total: 3.14s	remaining: 324ms
277:	learn: 0.1130262	total: 3.04s	remaining: 241ms
271:	learn: 0.1140730	total: 2.83s	remaining: 292ms
275:	learn: 0.1151954	total: 3s	remaining: 261ms
272:	learn: 0.1168999	total: 3.15s	remaining: 311ms
273:	learn: 0.1168203	total: 3.02s	remaining: 287ms
272:	learn: 0.1140295	total: 2.84s	remaining: 281ms
278:	learn: 0.1129894	total: 3.05s	remaining: 229ms
276:	learn: 0.1151762	total: 3.01s	remaining: 250ms
273:	learn: 0.1168889	total: 3.15s	remaining: 299ms
279:	learn: 0.1129585	total: 3.05s	remaining: 218ms
273:	learn: 0.1140072	total: 2.84s	remaining: 270ms
274:	learn: 0.1167885	total: 3.03s	remaining: 275ms
277:	learn: 0.1151205	total: 3.01s	remaining: 238ms
274:	learn: 0.1139783	total: 2.84s	remaining: 258ms
274:	learn: 0.1168680	total: 3.15s	remaining: 287ms
280:	learn: 0.1129236	total: 3.06s	remaining: 207ms
278:	learn: 0.1150917	total: 3.01s	remaining: 227ms
275:	learn: 0.1167551	total: 3.03s	remaining: 264ms
275:	learn: 0.1139241	total: 2.85s	remaining: 247ms
275:	learn: 0.1168384	total: 3.16s	remaining: 275ms
276:	learn: 0.1167361	total: 3.04s	remaining: 252ms
279:	learn: 0.1150600	total: 3.02s	remaining: 216ms
281:	learn: 0.1128894	total: 3.06s	remaining: 195ms
276:	learn: 0.1139100	total: 2.85s	remaining: 237ms
276:	learn: 0.1168010	total: 3.16s	remaining: 263ms
280:	learn: 0.1150307	total: 3.02s	remaining: 204ms
282:	learn: 0.1128623	total: 3.06s	remaining: 184ms
277:	learn: 0.1167052	total: 3.04s	remaining: 241ms
277:	learn: 0.1167690	total: 3.17s	remaining: 251ms
277:	learn: 0.1138917	total: 2.85s	remaining: 226ms
281:	learn: 0.1149871	total: 3.02s	remaining: 193ms
278:	learn: 0.1167321	total: 3.17s	remaining: 239ms
278:	learn: 0.1166884	total: 3.05s	remaining: 229ms
283:	learn: 0.1128287	total: 3.07s	remaining: 173ms
278:	learn: 0.1138626	total: 2.86s	remaining: 215ms
279:	learn: 0.1166948	total: 3.17s	remaining: 227ms
282:	learn: 0.1149684	total: 3.03s	remaining: 182ms
284:	learn: 0.1128154	total: 3.07s	remaining: 162ms
279:	learn: 0.1166628	total: 3.05s	remaining: 218ms
279:	learn: 0.1138418	total: 2.86s	remaining: 204ms
280:	learn: 0.1166621	total: 3.18s	remaining: 215ms
280:	learn: 0.1138196	total: 2.87s	remaining: 194ms
280:	learn: 0.1166415	total: 3.05s	remaining: 207ms
285:	learn: 0.1127611	total: 3.08s	remaining: 151ms
283:	learn: 0.1149520	total: 3.03s	remaining: 171ms
286:	learn: 0.1127243	total: 3.08s	remaining: 140ms
281:	learn: 0.1138064	total: 2.87s	remaining: 183ms
284:	learn: 0.1149244	total: 3.04s	remaining: 160ms
281:	learn: 0.1166239	total: 3.06s	remaining: 195ms
281:	learn: 0.1166248	total: 3.18s	remaining: 203ms
287:	learn: 0.1126945	total: 3.08s	remaining: 128ms
285:	learn: 0.1148992	total: 3.04s	remaining: 149ms
282:	learn: 0.1137829	total: 2.87s	remaining: 173ms
282:	learn: 0.1165790	total: 3.19s	remaining: 191ms
282:	learn: 0.1166086	total: 3.06s	remaining: 184ms
288:	learn: 0.1126616	total: 3.09s	remaining: 117ms
286:	learn: 0.1148660	total: 3.04s	remaining: 138ms
283:	learn: 0.1137406	total: 2.88s	remaining: 162ms
283:	learn: 0.1165318	total: 3.19s	remaining: 180ms
289:	learn: 0.1126482	total: 3.09s	remaining: 107ms
287:	learn: 0.1148315	total: 3.05s	remaining: 127ms
283:	learn: 0.1165869	total: 3.07s	remaining: 173ms
284:	learn: 0.1137119	total: 2.88s	remaining: 152ms
284:	learn: 0.1164955	total: 3.19s	remaining: 168ms
290:	learn: 0.1126238	total: 3.09s	remaining: 95.6ms
288:	learn: 0.1147468	total: 3.05s	remaining: 116ms
284:	learn: 0.1165612	total: 3.07s	remaining: 162ms
285:	learn: 0.1164663	total: 3.19s	remaining: 156ms
289:	learn: 0.1146711	total: 3.05s	remaining: 105ms
285:	learn: 0.1136465	total: 2.88s	remaining: 141ms
291:	learn: 0.1125940	total: 3.1s	remaining: 84.9ms
286:	learn: 0.1164259	total: 3.2s	remaining: 145ms
285:	learn: 0.1165207	total: 3.07s	remaining: 151ms
292:	learn: 0.1125565	total: 3.1s	remaining: 74.1ms
287:	learn: 0.1163479	total: 3.2s	remaining: 133ms
286:	learn: 0.1136131	total: 2.89s	remaining: 131ms
290:	learn: 0.1146503	total: 3.06s	remaining: 94.6ms
286:	learn: 0.1164938	total: 3.08s	remaining: 139ms
287:	learn: 0.1164805	total: 3.08s	remaining: 128ms
293:	learn: 0.1125284	total: 3.1s	remaining: 63.3ms
287:	learn: 0.1135945	total: 2.89s	remaining: 121ms
288:	learn: 0.1163140	total: 3.2s	remaining: 122ms
291:	learn: 0.1146274	total: 3.06s	remaining: 83.9ms
288:	learn: 0.1164535	total: 3.08s	remaining: 117ms
289:	learn: 0.1162933	total: 3.21s	remaining: 111ms
292:	learn: 0.1146104	total: 3.06s	remaining: 73.2ms
288:	learn: 0.1135797	total: 2.9s	remaining: 110ms
294:	learn: 0.1124946	total: 3.11s	remaining: 52.7ms
289:	learn: 0.1164215	total: 3.09s	remaining: 106ms
290:	learn: 0.1162621	total: 3.21s	remaining: 99.3ms
295:	learn: 0.1124676	total: 3.11s	remaining: 42ms
293:	learn: 0.1145907	total: 3.07s	remaining: 62.6ms
289:	learn: 0.1135592	total: 2.9s	remaining: 100ms
291:	learn: 0.1162413	total: 3.21s	remaining: 88ms
290:	learn: 0.1163948	total: 3.09s	remaining: 95.6ms
290:	learn: 0.1135006	total: 2.9s	remaining: 89.8ms
296:	learn: 0.1124555	total: 3.12s	remaining: 31.5ms
291:	learn: 0.1163723	total: 3.09s	remaining: 84.7ms
291:	learn: 0.1134852	total: 2.9s	remaining: 79.6ms
294:	learn: 0.1145718	total: 3.07s	remaining: 52.1ms
292:	learn: 0.1162291	total: 3.22s	remaining: 76.9ms
292:	learn: 0.1163514	total: 3.1s	remaining: 74ms
292:	learn: 0.1134645	total: 2.91s	remaining: 69.5ms
297:	learn: 0.1124251	total: 3.12s	remaining: 20.9ms
295:	learn: 0.1145036	total: 3.08s	remaining: 41.6ms
293:	learn: 0.1162054	total: 3.22s	remaining: 65.7ms
293:	learn: 0.1163327	total: 3.1s	remaining: 63.3ms
293:	learn: 0.1134400	total: 2.91s	remaining: 59.4ms
298:	learn: 0.1124085	total: 3.12s	remaining: 10.4ms
294:	learn: 0.1161773	total: 3.22s	remaining: 54.6ms
296:	learn: 0.1144883	total: 3.08s	remaining: 31.1ms
294:	learn: 0.1133873	total: 2.91s	remaining: 49.4ms
299:	learn: 0.1123779	total: 3.13s	remaining: 0us

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

In [48]:
preds_stack

array([1, 0, 1, ..., 1, 1, 0], shape=(6175,))

In [56]:
predictions = stacking.predict(X_test)
reverse_mapping = {1: 'Extrovert', 0: 'Introvert'}
final_predictions_text = pd.Series(predictions).map(reverse_mapping)

submission_df = pd.DataFrame({'id': test_df['id'], 'Personality': final_predictions_text})
submission_df.to_csv('submission_stacking.csv', index=False)

print("\nSubmission file 'submission.csv' created successfully.")
print("Submission file head:")
print(submission_df.head())

Submission file 'submission.csv' created successfully.
Submission file head:
      id Personality
0  18524   Extrovert
1  18525   Introvert
2  18526   Extrovert
3  18527   Extrovert
4  18528   Introvert

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

In [44]:
preds_stack

,0,1,2,3,4,5,6,7,8,9,...,6165,6166,6167,6168,6169,6170,6171,6172,6173,6174
id,,,,,,,,,,,,,,,,,,,,,
18524,1,0,1,1,0,1,1,0,1,0,...,1,1,1,1,1,1,0,1,1,0
18525,1,0,1,1,0,1,1,0,1,0,...,1,1,1,1,1,1,0,1,1,0
18526,1,0,1,1,0,1,1,0,1,0,...,1,1,1,1,1,1,0,1,1,0
18527,1,0,1,1,0,1,1,0,1,0,...,1,1,1,1,1,1,0,1,1,0
18528,1,0,1,1,0,1,1,0,1,0,...,1,1,1,1,1,1,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24694,1,0,1,1,0,1,1,0,1,0,...,1,1,1,1,1,1,0,1,1,0
24695,1,0,1,1,0,1,1,0,1,0,...,1,1,1,1,1,1,0,1,1,0
24696,1,0,1,1,0,1,1,0,1,0,...,1,1,1,1,1,1,0,1,1,0
24697,1,0,1,1,0,1,1,0,1,0,...,1,1,1,1,1,1,0,1,1,0
24698,1,0,1,1,0,1,1,0,1,0,...,1,1,1,1,1,1,0,1,1,0